export const DEFAULT_STATUS_OPTIONS = [
  { value: 'published', label: 'Published' },
  { value: 'draft', label: 'Draft' },
  { value: 'archived', label: 'Archived' },
  { value: 'active', label: 'Active' },
  { value: 'inactive', label: 'Inactive' },
  { value: 'new', label: 'New' },
  { value: 'in_progress', label: 'In Progress' },
  { value: 'resolved', label: 'Resolved' },
]

export const CATEGORY_STATUS_OPTIONS = [
  { value: 'active', label: 'Active' },
  { value: 'inactive', label: 'Inactive' },
]

export const CONTENT_STATUS_OPTIONS = [
  { value: 'draft', label: 'Draft' },
  { value: 'published', label: 'Published' },
  { value: 'archived', label: 'Archived' },
]

export const ENTITY_MANAGER_CONFIGS = {
  pages: {
    label: 'Trang Nội Dung',
    eyebrow: 'Danh sách các trang CMS',
    description: 'Quản lý các trang nội dung chính của website. Đối với luồng Giới thiệu, bảng này chỉ nên giữ một bản ghi trang cha duy nhất là `about`, trong khi các phần chi tiết được quản lý trong mục Phần Trang và Khối Nội Dung.',
    titleField: 'title',
    editorPresentation: 'modal',
    table: ['id', 'title', 'slug', 'page_type', 'status', 'language_id', 'sort_order'],
    required: ['slug', 'language_id'],
    fields: ['slug', 'title', 'summary', 'body', 'page_type', 'language_id', 'parent_id', 'status', 'meta_title', 'meta_description', 'sort_order'],
    statusOptions: CONTENT_STATUS_OPTIONS,
    defaultStatus: 'draft',
    preview: (record) => `/${record.slug}`,
    fieldLabels: {
      slug: 'Đường dẫn (Slug)',
      title: 'Tiêu đề trang',
      summary: 'Tóm tắt ngắn',
      body: 'Nội dung chi tiết',
      page_type: 'Loại trang',
      language_id: 'Ngôn ngữ',
      parent_id: 'Trang cha',
      status: 'Trạng thái xuất bản',
      meta_title: 'SEO Meta Title',
      meta_description: 'SEO Meta Description',
      title_en: 'Ten Du An (EN)',
      title_zh: 'Ten Du An (ZH)',
      summary_en: 'Mo Ta Ngan (EN)',
      summary_zh: 'Mo Ta Ngan (ZH)',
      body_en: 'Mo Ta Chi Tiet (EN)',
      body_zh: 'Mo Ta Chi Tiet (ZH)',
      location_en: 'Dia Diem (EN)',
      location_zh: 'Dia Diem (ZH)',
      meta_title_en: 'SEO Title (EN)',
      meta_title_zh: 'SEO Title (ZH)',
      meta_description_en: 'SEO Description (EN)',
      meta_description_zh: 'SEO Description (ZH)',
      sort_order: 'Thứ tự hiển thị',
    },
    placeholders: {
      title_en: 'Example: Hengtong Building',
      title_zh: 'Chinese project title...',
      slug: 'hengtong-building',
      summary_en: 'Short English project summary...',
      summary_zh: 'Chinese project summary...',
      body_en: 'Detailed English project content...',
      body_zh: 'Detailed Chinese project content...',
      location_en: 'Example: Guangzhou, China',
      location_zh: 'Example: Guangzhou, China',
      title_en: 'Example: Hengtong Building',
      title_zh: 'Chinese project title...',
      slug: 'hengtong-building',
      summary_en: 'Short English project summary...',
      summary_zh: 'Chinese project summary...',
      body_en: 'Detailed English project content...',
      body_zh: 'Detailed Chinese project content...',
      location_en: 'Example: Guangzhou, China',
      location_zh: 'Example: Guangzhou, China',
      slug: 'Ví dụ: about',
      title: 'Ví dụ: Giới thiệu công ty',
      summary: 'Tóm tắt ngắn gọn của trang dùng cho SEO và API công khai.',
      body: 'Nội dung chi tiết (không bắt buộc nếu dùng các khối nội dung).',
      page_type: 'Ví dụ: about',
      meta_title: 'Tiêu đề SEO hiển thị trên tab trình duyệt.',
      meta_description: 'Mô tả SEO ngắn gọn cho trang.',
    },
    helpText: {
      slug: 'Đối với trang Giới thiệu hiện tại, hãy giữ nguyên slug `about`. Không tạo thêm các hàng riêng biệt cho từng phần như introduction hay vision.',
      page_type: 'Sử dụng tên nhóm ổn định như about, legal hoặc contact.',
      parent_id: 'Thường để trống cho các trang cấp cao nhất.',
      status: 'Chỉ các trang được "Published" mới hiển thị trên website.',
      meta_title: 'Khuyên dùng cho SEO. Nếu để trống sẽ dùng tiêu đề trang.',
      meta_description: 'Khuyên dùng cho SEO và xem trước trên mạng xã hội.',
      sort_order: 'Dùng 10, 20, 30... để dễ dàng sắp xếp lại thứ tự sau này.',
    },
  },
  page_sections: {
    label: 'Các Phần Trang',
    eyebrow: 'Cấu trúc các phần của trang',
    description: 'Quản lý các phần cấu trúc bên trong một trang CMS. Ví dụ với trang Giới thiệu, bảng này chứa các phần: Hero, Giới thiệu công ty, Tầm nhìn & Sứ mệnh, Sơ đồ tổ chức, Giá trị cốt lõi, Lịch sử phát triển, Ban lãnh đạo.',
    titleField: 'title',
    editorPresentation: 'modal',
    hideMediaGallery: true,
    table: ['id', 'page_id', 'title', 'anchor', 'section_type', 'sort_order'],
    required: ['page_id'],
    fields: ['page_id', 'anchor', 'title', 'content', 'image_id', 'section_type', 'sort_order'],
    preview: (record) => {
      if (record.preview_href) {
        return record.preview_href
      }

      if (record.page_slug === 'about') {
        const aboutRouteMap = {
          hero: '/about/company-introduction#page1',
          company_introduction: '/about/company-introduction#page2',
          chairman_speech: '/about/chairman-speech#page3',
          organization_chart: '/about/organization-chart#page4',
          corporate_culture: '/about/corporate-culture#page5',
          development_course: '/about/development-course#page6',
          leadership_care: '/about/leadership-care#page7',
        }
        return aboutRouteMap[record.anchor] || '/about/company-introduction#page1'
      }

      if (record.page_slug) {
        return `/${record.page_slug}${record.anchor ? `#${record.anchor}` : ''}`
      }

      return ''
    },
    fields: ['title', 'content', 'image_id', 'sort_order'],
    fieldLabels: {
      title: 'Tên mục hiển thị',
      content: 'Ghi chú (Nội bộ)',
      image_id: 'Ảnh đại diện/Ảnh nền',
      sort_order: 'Thứ tự',
    },
    helpText: {
      page_id: 'Chọn trang cha mà phần này thuộc về. Với trang Giới thiệu, tất cả các phần nên thuộc về trang `about`.',
      anchor: 'Mã kỹ thuật dùng để link chính xác đến phần đó trên web. KHÔNG đổi khi không cần thiết.',
      image_id: 'Ảnh nền hoặc ảnh đại diện cho phần này.',
      section_type: 'Phân loại loại mục để FE xử lý style tương ứng.',
      sort_order: 'Dùng 10, 20, 30... để kiểm soát thứ tự từ trên xuống dưới.',
      content: 'Dùng như ghi chú nội bộ để người quản trị biết phần này điều khiển nội dung nào.',
    },
  },
  content_blocks: {
    label: 'Khối Nội Dung',
    eyebrow: 'Các khối nội dung CMS',
    description: 'Quản lý các khối nội dung lớn gắn với một trang. Đối với trang Giới thiệu, các khối nên gắn với Loai đối tượng = page và ID bản ghi = id của trang `about` (thường là 1).',
    recordDisplayName: (record) => {
      const translations = {
        'hero_summary': '1. Tên công ty & Slogan',
        'hero_nav': '2. Menu điều hướng trang',
        'intro_media': '3. Hình ảnh/Video giới thiệu',
        'intro_video': '4. Nút bấm xem Video',
        'intro_paragraphs': '5. Các đoạn văn giới thiệu',
        'speech_profile': '6. Ảnh chân dung Lãnh đạo',
        'speech_body': '7. Văn bản Tầm nhìn & Sứ mệnh',
        'speech_signature': '8. Chữ ký Lãnh đạo',
        'org_chart_image': '9. Sơ đồ tổ chức',
        'culture_values': '10. Giá trị cốt lõi',
        'culture_slogan': '11. Slogan',
        'timeline': '12. Lịch sử phát triển',
        'leadership_care_gallery': '13. Ban lãnh đạo (Album)',
      }
      const rawKey = String(record?.block_key || record?.title || '').toLowerCase().trim();
      // Try to find a match by comparing lowercase keys
      const matchedKey = Object.keys(translations).find(k => k.toLowerCase() === rawKey);
      return matchedKey ? translations[matchedKey] : (record?.block_key || record?.title || '');
    },
    table: ['id', 'block_key', 'block_type', 'sort_order'],
    required: ['entity_id', 'block_key', 'block_type'],
    fields: ['entity_id', 'block_key', 'block_type', 'title', 'sort_order'],
    fieldLabels: {
      entity_type: 'Loại trang',
      entity_id: 'ID Trang',
      language_id: 'Ngôn ngữ',
      block_key: 'Mã định danh nhóm',
      title: 'Tiêu đề nhóm (Nếu có)',
      subtitle: 'Phụ đề nhóm',
      content: 'Mô tả nội bộ',
      block_type: 'Loại hiển thị',
      sort_order: 'Thứ tự ưu tiên',
    },
    relationEntities: {
      entity_id: 'pages',
    },
    fieldLabels: {
      entity_type: 'Loại thực thể',
      entity_id: 'ID bản ghi trang',
      language_id: 'Ngôn ngữ',
      block_key: 'Mã định danh khối',
      title: 'Tiêu đề khối',
      subtitle: 'Phụ đề khối',
      content: 'Nội dung khối',
      block_type: 'Loại khối',
      sort_order: 'Thứ tự hiển thị',
    },
    placeholders: {
      entity_type: 'Ví dụ: page',
      entity_id: 'ID của bản ghi trang liên quan',
      block_key: 'Ví dụ: intro_paragraphs',
      title: 'Tiêu đề khối (tùy chọn)',
      subtitle: 'Phụ đề khối (tùy chọn)',
      content: 'Nội dung văn bản dài (tùy chọn)',
      block_type: 'Ví dụ: rich_text_list, timeline, logo_grid',
    },
    helpText: {
      entity_type: 'Đối với trang Giới thiệu, hãy khóa giá trị này là `page`.',
      entity_id: 'Nhập ID của bản ghi trang mà khối này thuộc về.',
      block_key: 'Mã định danh ổn định. Ví dụ: intro_paragraphs (giới thiệu), speech_body (tầm nhìn), culture_values/culture_slogan (giá trị & slogan), timeline (lịch sử), leadership_profiles (lãnh đạo).',
      block_type: 'Phân loại loại khối: rich_text_list, media_profile, timeline, carousel_cards.',
      sort_order: 'Dùng 10, 20, 30... để kiểm soát thứ tự khối trong cùng một trang.',
    },
  },
  content_block_items: {
    label: 'Mục Chi Tiết (Khối)',
    eyebrow: 'Chi tiết bên trong khối nội dung',
    description: 'Quản lý các mục con bên trong mỗi khối nội dung, ví dụ: các đoạn văn, mốc lịch sử, hồ sơ ban lãnh đạo, logo đối tác.',
    titleField: 'title',
    editorPresentation: 'modal',
    hideMediaGallery: true,
    recordDisplayName: (record) => {
      const translations = {
        'hero_summary': '1. Tên công ty & Slogan',
        'intro_paragraphs': '5. Văn bản giới thiệu',
        'cover_image': 'Ảnh bìa/Ảnh nền',
        'paragraph_1': 'Đoạn văn số 1',
        'paragraph_2': 'Đoạn văn số 2',
        'paragraph_3': 'Đoạn văn số 3',
        'portrait': 'Ảnh chân dung lãnh đạo',
        'sign_name': 'Họ tên lãnh đạo',
        'sign_title': 'Chức danh lãnh đạo',
        'visit_1': 'Mục lịch sử/Lãnh đạo 1',
        'milestone_1': 'Mốc lịch sử 1',
        'milestone_2': 'Mốc lịch sử 2',
      }
      const rawTitle = record?.title || '';
      const rawKey = String(record?.item_key || '').toLowerCase().trim();
      return rawTitle || translations[rawKey] || rawKey || `#${record?.id}`;
    },
    table: ['id', 'block_id', 'title', 'item_key', 'sort_order'],
    required: ['block_id', 'item_key'],
    fields: [
      'block_id', 'item_key',
      'title', 'title_en', 'title_zh',
      'subtitle', 'subtitle_en', 'subtitle_zh',
      'content', 'content_en', 'content_zh',
      'link', 'image_id', 'sort_order',
    ],
    fieldLabels: {
      block_id: 'Thuộc nhóm nội dung',
      item_key: 'Mã mục (item_key)',
      title: 'Tên mục (Để bạn dễ tìm)',
      subtitle: 'Phụ đề / Chức vụ / Năm-Tháng',
      content: 'Nội dung chi tiết / Văn bản',
      link: 'Liên kết / URL',
      image_id: 'Hình ảnh / Logo / Sơ đồ',
      sort_order: 'Thứ tự hiển thị (10, 20...)',
    },
    optionLabel: (option, field) => {
      if (field === 'block_id') {
        const translations = {
          'About Hero Summary': '1. Tên công ty & Slogan',
          'About Navigation Tabs': '2. Menu điều hướng trang',
          'Company Introduction Media': '3. Hình ảnh/Video giới thiệu',
          'Company Introduction Text': '4. Nội dung bài viết giới thiệu',
          'Chairman Portrait': '5. Ảnh chân dung lãnh đạo',
          'Chairman\'s Speech Text': '6. Văn bản Tầm nhìn & Sứ mệnh',
          'Chairman Signature': '7. Chữ ký lãnh đạo',
          'Organization Chart': '8. Sơ đồ tổ chức',
          'Corporate Culture': '9. Giá trị cốt lõi',
          'Development Course Timeline': '10. Lịch sử phát triển',
          'Leadership Care Gallery': '11. Danh sách ban lãnh đạo',
        }
        const key = option.title || option.name || ''
        return translations[key] || `#${option.id} - ${key}`
      }
      return `#${option.id} - ${option.title || option.name || option.slug}`
    },
    placeholders: {
      item_key: 'Ví dụ: paragraph_1, vision, mission, value_1, milestone_1, leader_1',
      title: 'Ví dụ: Nguyễn Văn A hoặc Thành lập công ty',
      subtitle: 'Ví dụ: Giám đốc Điều hành hoặc 2024-01 (timeline)',
      content: 'Nhập nội dung văn bản cho mục này.',
      link: 'https://example.com hoặc /internal-path',
    },
    helpText: {
      block_id: 'Chọn khối cha trước. Các mục sẽ luôn hiển thị bên trong khối này.',
      item_key: 'Mã kỹ thuật định danh mục. Bắt buộc theo chuẩn từng block (ví dụ: vision/mission, value_1, milestone_1, leader_1...).',
      subtitle: 'Dùng cho chức vụ ở Ban lãnh đạo. Riêng timeline, nhập Năm/Tháng dạng 2024 hoặc 2024-01.',
      image_id: 'Ảnh đại diện cho cá nhân (Ban lãnh đạo), ảnh mốc lịch sử hoặc logo đối tác.',
      link: 'Dùng cho mục cần gắn URL ngoài hoặc đường dẫn nội bộ.',
      sort_order: 'Dùng 10, 20, 30... để sắp xếp thứ tự các mục bên trong khối.',
    },
  },
  banners: {
    label: 'Banners',
    eyebrow: 'Hero and section banners',
    description: 'Manage banners, CTA buttons, type, language, and display order.',
    titleField: 'title',
    table: ['id', 'title', 'banner_type', 'placement', 'sort_order', 'is_active'],
    required: ['placement'],
    fields: ['title', 'subtitle', 'body', 'image_id', 'focus_x', 'focus_y', 'link', 'button_text', 'banner_type', 'placement', 'sort_order', 'is_active'],
    statusOptions: [
      { value: 'active', label: 'Active' },
      { value: 'inactive', label: 'Inactive' },
    ],
    selectOptions: {
      banner_type: [
        { value: 'hero', label: 'Hero (Main Slider)' },
        { value: 'cta', label: 'CTA (Call to Action)' },
        { value: 'secondary', label: 'Secondary Banner' },
        { value: 'video_bg', label: 'Video Background' },
      ],
      placement: [
        { value: 'home', label: 'Trang chủ (Home)' },
        { value: 'about', label: 'Giới thiệu (About)' },
        { value: 'products', label: 'Sản phẩm (Products)' },
        { value: 'news', label: 'Tin tức (News)' },
        { value: 'contact', label: 'Liên hệ (Contact)' },
        { value: 'global', label: 'Toàn trang (Global)' },
      ],
    },
    defaultStatus: 'active',
    previewMediaField: 'image_id',
    mediaUploadTargetField: 'image_id',
    mediaUploadAccept: 'image/*,video/*',
    cloudinaryAssetFolder: 'banner',
    fieldLabels: {
      title: 'Banner Title',
      subtitle: 'Subtitle',
      body: 'Description',
      image_id: 'Ảnh/Video Banner',
      focus_x: 'Điểm lấy nét X',
      focus_y: 'Điểm lấy nét Y',
      link: 'Liên kết CTA',
      button_text: 'Nhãn nút',
      banner_type: 'Loại banner',
      placement: 'Vị trí hiển thị',
      language_id: 'Ngôn ngữ',
      sort_order: 'Thứ tự hiển thị',
      is_active: 'Trạng thái',
    },
    placeholders: {
      title: 'Ví dụ: Chào mừng đến với China Decor',
      subtitle: 'Giải pháp nội thất cao cấp',
      body: 'Nhập mô tả ngắn cho banner này.',
      link: '/gioi-thieu hoặc https://example.com',
      button_text: 'Tìm hiểu thêm',
      placement: 'Chọn trang mà banner sẽ xuất hiện',
    },
    helpText: {
      image_id: 'Tải ảnh (JPG, PNG, WebP) hoặc video (MP4, WebM) dùng làm nền banner.',
      focus_x: 'Điểm lấy nét theo chiều ngang cho ảnh crop (0 đến 100).',
      focus_y: 'Điểm lấy nét theo chiều dọc cho ảnh crop (0 đến 100).',
      banner_type: 'Hero = slider trang chủ, CTA = thẻ quảng bá, Section/Page/Footer = vị trí phụ.',
      placement: 'Chọn chính xác trang mà bạn muốn banner này hiển thị.',
      link: 'URL sẽ mở khi người dùng nhấp vào banner hoặc nút CTA.',
      button_text: 'Nội dung hiển thị trên nút CTA (nếu có).',
      is_active: 'Chỉ banner đang bật mới hiển thị ở trang public.',
    },
    featuredTableFields: ['image_id', 'banner_type', 'placement', 'is_active'],
  },
  project_categories: {
    label: 'Project Categories',
    eyebrow: 'Project taxonomy',
    description: 'Manage public Project Case categories, legacy category ids, status, and hero media bindings.',
    titleField: 'name',
    pageSize: 25,
    table: ['id', 'name', 'slug', 'status', 'sort_order'],
    required: ['name', 'slug'],
    fields: ['name', 'slug', 'description', 'parent_id', 'sort_order', 'status'],
    statusOptions: CATEGORY_STATUS_OPTIONS,
    defaultStatus: 'active',
    preview: (record) => `/project_list/${record.id}.html`,
    fieldLabels: {
      name: 'Tên Danh Mục',
      slug: 'Slug (URL)',
      description: 'Mô Tả Danh Mục',
      parent_id: 'Danh Mục Cha',
      sort_order: 'Thứ Tự Hiển Thị',
      status: 'Trạng Thái',
    },
    placeholders: {
      name: 'Ví dụ: Khách Sạn 5 Sao',
      slug: 'khach-san-5-sao',
      description: 'Mô tả ngắn hiển thị trên banner hoặc metadata danh mục.',
    },
    helpText: {
      slug: 'Dùng cho tên chuẩn của taxonomy quản trị/dự án. Route public cũ hiện vẫn sử dụng category id dạng số.',
      sort_order: 'Kiểm soát thứ tự danh mục trong hero slider và sidebar của Project Case.',
      status: 'Chỉ danh mục đang hoạt động mới được public API trả ra.',
    },
  },
  projects: {
    label: 'Dự Án',
    eyebrow: 'Quản trị dự án',
    description: 'Chỉ giữ đúng các thông tin dự án theo requirement: tên dự án, hình ảnh, địa điểm, mô tả và sản phẩm sử dụng.',
    titleField: 'title',
    editorPresentation: 'modal',
    table: ['id', 'title', 'location', 'image_id', 'status'],
    required: ['title', 'slug', 'language_id'],
    fields: [
      'title', 'title_en', 'title_zh',
      'slug',
      'location', 'location_en', 'location_zh',
      'summary', 'summary_en', 'summary_zh',
      'body', 'body_en', 'body_zh',
      'image_id', 'hero_image_id',
      'category_id', 'project_year',
      'language_id', 'status',
      'meta_title', 'meta_title_en', 'meta_title_zh',
      'meta_description', 'meta_description_en', 'meta_description_zh',
    ],
    defaultValues: {
      language_id: 1,
      status: 'published',
    },
    relationEntities: {
      category_id: 'project_categories',
      language_id: 'languages',
    },
    mediaUploadTargetField: 'image_id',
    mediaUploadAccept: 'image/*',
    statusOptions: CONTENT_STATUS_OPTIONS,
    defaultStatus: 'published',
    preview: (record) => `/project/${record.slug}`,
    fieldLabels: {
      title: 'Tên Dự Án',
      slug: 'Slug (Tự Sinh)',
      category_id: 'Danh Mục',
      summary: 'Mô Tả',
      body: 'Mô Tả Chi Tiết',
      location: 'Địa Điểm',
      project_year: 'Năm Thực Hiện',
      image_id: 'Hình Ảnh Dự Án',
      hero_image_id: 'Ảnh Banner',
      language_id: 'Ngôn Ngữ',
      status: 'Trạng Thái',
      meta_title: 'SEO Meta Title',
      meta_description: 'SEO Meta Description',
      title_en: 'Ten Du An (EN)',
      title_zh: 'Ten Du An (ZH)',
      summary_en: 'Mo Ta Ngan (EN)',
      summary_zh: 'Mo Ta Ngan (ZH)',
      body_en: 'Mo Ta Chi Tiet (EN)',
      body_zh: 'Mo Ta Chi Tiet (ZH)',
      location_en: 'Dia Diem (EN)',
      location_zh: 'Dia Diem (ZH)',
      meta_title_en: 'SEO Title (EN)',
      meta_title_zh: 'SEO Title (ZH)',
      meta_description_en: 'SEO Description (EN)',
      meta_description_zh: 'SEO Description (ZH)',
    },
    placeholders: {
      title_en: 'Example: Hengtong Building',
      title_zh: 'Chinese project title...',
      slug: 'hengtong-building',
      summary_en: 'Short English project summary...',
      summary_zh: 'Chinese project summary...',
      body_en: 'Detailed English project content...',
      body_zh: 'Detailed Chinese project content...',
      location_en: 'Example: Guangzhou, China',
      location_zh: 'Example: Guangzhou, China',
      title: 'Ví dụ: Hengtong Building',
      summary: 'Nhập mô tả ngắn cho dự án.',
      body: 'Nhập mô tả chi tiết cho dự án nếu cần hiển thị ở trang chi tiết.',
      location: 'Ví dụ: Quảng Châu, Trung Quốc',
    },
    helpText: {
      title: 'Tên hiển thị chính của dự án.',
      summary: 'Đây là phần mô tả chính theo requirement.',
      body: 'Có thể dùng để lưu nội dung mô tả dài hơn cho trang chi tiết.',
      location: 'Địa điểm thực hiện dự án.',
      image_id: 'Chọn ảnh đại diện chính cho dự án. Nếu cần nhiều ảnh, dùng mục Hình Ảnh Dự Án ở sidebar.',
    },
  },
  project_category_items: {
    label: 'Gắn Dự Án Vào Danh Mục',
    eyebrow: 'Liên kết danh mục - dự án',
    description: 'Quản lý thứ tự Project Case, anchor, kiểu layout và trạng thái nổi bật của từng dự án trong mỗi danh mục.',
    titleField: 'anchor',
    pageSize: 25,
    table: ['id', 'category_id', 'project_id', 'anchor', 'sort_order', 'layout_variant', 'is_featured'],
    required: ['category_id', 'project_id', 'anchor', 'sort_order'],
    fields: ['category_id', 'project_id', 'sort_order', 'anchor', 'is_featured', 'layout_variant'],
    preview: (record) => `/project_list/${record.category_id}.html#${record.anchor}`,
    fieldLabels: {
      category_id: 'Danh Mục Dự Án',
      project_id: 'Dự Án',
      sort_order: 'Thứ Tự Hiển Thị',
      anchor: 'Anchor Section',
      is_featured: 'Layout Nổi Bật',
      layout_variant: 'Biến Thể Layout',
    },
    placeholders: {
      anchor: 'Ví dụ: ctn2',
      layout_variant: 'feature hoặc standard',
    },
    helpText: {
      category_id: 'Bắt buộc. Danh mục sở hữu section Project Case này.',
      project_id: 'Bắt buộc. Mỗi dự án chỉ nên xuất hiện một lần trong cùng một danh mục.',
      sort_order: 'Bắt buộc. Public API sẽ sắp xếp case theo giá trị này.',
      anchor: 'Bắt buộc. Phải là duy nhất trong danh mục đã chọn. Nên giữ pattern ctnX cũ để tương thích.',
      layout_variant: 'Frontend hiện dùng feature và standard. Chỉ đổi giá trị khi frontend đã được cập nhật tương ứng.',
    },
    relationEntities: {
      category_id: 'project_categories',
      project_id: 'projects',
    },
  },
  project_products: {
    label: 'Mapping Dự Án - Sản Phẩm',
    eyebrow: 'Project to product mapping',
    description: 'Liên kết sản phẩm sử dụng trong từng dự án để section public "Sản phẩm sử dụng" render hoàn toàn từ CMS.',
    titleField: 'id',
    pageSize: 25,
    table: ['id', 'project_id', 'product_id', 'sort_order', 'note'],
    required: ['project_id', 'product_id'],
    fields: ['project_id', 'product_id', 'sort_order', 'note'],
    preview: () => '',
    fieldLabels: {
      project_id: 'Dự Án',
      product_id: 'Sản Phẩm',
      sort_order: 'Thứ Tự Hiển Thị',
      note: 'Ghi Chú Ứng Dụng',
    },
    placeholders: {
      note: 'Ví dụ: Dùng cho khu vực sảnh chính, vách trang trí, trần hành lang...',
    },
    helpText: {
      project_id: 'Chọn dự án cần gắn sản phẩm.',
      product_id: 'Chọn sản phẩm thực tế đã sử dụng trong dự án này.',
      sort_order: 'Dùng 10, 20, 30... để kiểm soát thứ tự card ở trang chi tiết dự án.',
      note: 'Ghi chú ngắn để mô tả ngữ cảnh ứng dụng của sản phẩm trong công trình.',
    },
    relationEntities: {
      project_id: 'projects',
      product_id: 'products',
    },
  },
  entity_media: {
    label: 'Nhóm Media Dự Án',
    eyebrow: 'Liên kết media theo entity',
    description: 'Liên kết hero và gallery media cho danh mục dự án và dự án thông qua các group trong entity_media.',
    titleField: 'group_name',
    pageSize: 25,
    table: ['id', 'entity_type', 'entity_id', 'group_name', 'media_id', 'sort_order'],
    required: ['entity_type', 'entity_id', 'media_id', 'group_name', 'sort_order'],
    fields: ['entity_type', 'entity_id', 'media_id', 'group_name', 'sort_order', 'caption'],
    defaultValues: {
      entity_type: 'project_category',
      group_name: 'hero_desktop',
    },
    selectOptions: {
      entity_type: [
        { value: 'project_category', label: 'Danh mục dự án' },
        { value: 'project', label: 'Dự án' },
      ],
      group_name: [
        { value: 'hero_desktop', label: 'Hero desktop' },
        { value: 'hero_mobile', label: 'Hero mobile' },
        { value: 'left_gallery', label: 'Gallery trái' },
        { value: 'right_gallery', label: 'Gallery phải' },
      ],
    },
    selectOptionsByEntityType: {
      group_name: {
        project_category: [
          { value: 'hero_desktop', label: 'Hero desktop' },
          { value: 'hero_mobile', label: 'Hero mobile' },
        ],
        project: [
          { value: 'left_gallery', label: 'Gallery trái' },
          { value: 'right_gallery', label: 'Gallery phải' },
        ],
      },
    },
    preview: (record) => {
      if (record.preview_href) {
        return record.preview_href
      }
      if (record.entity_type === 'project_category') {
        return `/project_list/${record.entity_id}.html`
      }
      if (record.entity_type === 'project' && record.entity_slug) {
        return `/project/${record.entity_slug}`
      }
      return ''
    },
    fieldLabels: {
      entity_type: 'Loại Entity',
      entity_id: 'Bản Ghi Entity',
      media_id: 'Tài Nguyên Media',
      group_name: 'Nhóm Media',
      sort_order: 'Thứ Tự Hiển Thị',
      caption: 'Chú Thích',
    },
    placeholders: {
      entity_id: 'Chọn bản ghi danh mục hoặc dự án từ danh sách',
      group_name: 'hero_desktop, hero_mobile, left_gallery, right_gallery',
      caption: 'Chú thích tùy chọn để dùng về sau',
    },
    helpText: {
      entity_type: 'Dùng project_category cho ảnh hero danh mục, project cho gallery dự án.',
      entity_id: 'Danh sách sẽ tự cập nhật theo Loại Entity để bạn gắn media mà không cần nhập tay id số. Hãy dùng link xem trước nội tuyến để kiểm tra đúng đích trước khi lưu.',
      group_name: 'Các tùy chọn nhóm sẽ được lọc theo Loại Entity: danh mục dự án dùng hero_desktop/hero_mobile, dự án dùng left_gallery/right_gallery.',
      sort_order: 'Kiểm soát thứ tự ảnh trong nhóm media đã chọn.',
    },
  },
  contacts: {
    label: 'Contacts',
    eyebrow: 'Contact information',
    description: 'Manage contact points, map links, phone numbers, email, and branch assignments.',
    titleField: 'name',
    table: ['id', 'name', 'contact_type', 'postal_code', 'phone', 'email', 'is_primary', 'language_id'],
    required: ['name', 'language_id', 'latitude', 'longitude'],
    fields: ['name', 'contact_type', 'address', 'postal_code', 'phone', 'email', 'map_url', 'latitude', 'longitude', 'branch_id', 'is_primary', 'language_id'],
    fieldLabels: {
      name: 'Tên Liên Hệ / Chi Nhánh',
      contact_type: 'Loại Liên Hệ',
      address: 'Địa Chỉ',
      postal_code: 'Mã Bưu Chính',
      phone: 'Số Điện Thoại',
      email: 'Email',
      map_url: 'Link Google Maps',
      latitude: 'Vĩ Độ (Lat)',
      longitude: 'Kinh Độ (Lng)',
      branch_id: 'Chi Nhánh',
      is_primary: 'Liên Hệ Chính',
      language_id: 'Ngôn Ngữ',
    }
  },
  honors: {
    label: 'Năng Lực',
    eyebrow: 'Factory profile and capability',
    description: 'Quản lý hình ảnh nhà máy, công nghệ sản xuất, công suất, chứng nhận ISO & CE và nội dung năng lực.',
    titleField: 'title',
    table: ['id', 'title', 'award_category', 'issuer', 'sort_order', 'is_active'],
    required: ['title', 'language_id'],
    fields: ['title', 'description', 'award_year', 'award_category', 'project_id', 'image_id', 'issuer', 'language_id', 'sort_order', 'is_active'],
    preview: () => '/honors',
    statusOptions: CONTENT_STATUS_OPTIONS,
    defaultStatus: 'published',
    fieldLabels: {
      title: 'Tiêu Đề',
      description: 'Mô Tả Ngắn',
      award_year: 'Năm / Mốc',
      award_category: 'Nhóm Nội Dung',
      project_id: 'Dự Án Liên Kết',
      image_id: 'Ảnh Đại Diện',
      issuer: 'Nguồn / Đơn Vị',
      language_id: 'Ngôn Ngữ',
      sort_order: 'Thứ Tự Hiển Thị',
      is_active: 'Đang Hiển Thị',
    },
    placeholders: {
      title: 'Ví dụ: Hình ảnh nhà máy',
      description: 'Mô tả ngắn cho mục năng lực này.',
      award_year: '2024',
      award_category: 'factory_images / production_technology / output / certificate',
      issuer: 'Ví dụ: Nhà máy Bắc Kinh',
    },
    helpText: {
      award_category: 'Dùng để phân nhóm nội dung năng lực: factory_images, production_technology, output, certificate.',
      image_id: 'Ảnh thực tế của nhà máy, máy móc hoặc chứng nhận. Đây là nội dung công khai của trang Năng lực.',
      sort_order: 'Dùng 10, 20, 30... để sắp xếp thứ tự hiển thị.',
      is_active: 'Chỉ mục đang hiển thị mới xuất hiện trên trang public.',
    },
  },
  videos: {
    label: 'Video',
    eyebrow: 'Thu vien video',
    description: 'Quan ly video san pham: gan video voi san pham, ho tro upload file hoac dan URL video.',
    titleField: 'title',
    table: ['id', 'title', 'product_name', 'video_url', 'status'],
    required: ['title', 'product_id', 'video_url'],
    fields: ['title', 'product_id', 'video_url', 'status'],
    statusOptions: CONTENT_STATUS_OPTIONS,
    defaultStatus: 'draft',
    preview: () => '/video',
    cloudinaryAssetFolder: 'videos',
    fieldLabels: {
      title: 'Tieu De Video',
      product_id: 'San Pham Lien Ket',
      product_name: 'San Pham',
      video_url: 'Duong Dan Video',
      status: 'Trang Thai Hien Thi',
    },
    placeholders: {
      title: 'Vi du: Video demo san pham',
      product_id: 'Tim kiem hoac chon san pham',
      video_url: 'https://cdn.example.com/showcase/video.mp4 hoac URL YouTube/Vimeo',
    },
    helpText: {
      product_id: 'Moi video phai thuoc mot san pham. Ban co the go tim theo ten, SKU hoac slug.',
      video_url: 'Dung URL MP4/WebM truc tiep hoac lien ket YouTube/Vimeo/share hop le. Frontend se mo bang player cao cap.',
      status: 'Chi video co trang thai xuat ban moi hien thi tren trang public.',
    },
    relationEntities: {
      product_id: 'products',
    },
    featuredTableFields: ['product_name', 'video_url', 'status'],
  },
  media_assets: {
    label: 'Thư Viện Media',
    eyebrow: 'Tài nguyên đã tải lên',
    description: 'Tải lên, rà soát và cập nhật hình ảnh, tệp video hoặc tài liệu PDF được sử dụng trên toàn bộ website.',
    titleField: 'title',
    table: ['id', 'title', 'file_name', 'asset_type', 'mime_type', 'status'],
    required: ['uuid', 'url', 'asset_type'],
    fields: ['uuid', 'file_name', 'url', 'storage_path', 'asset_type', 'mime_type', 'width', 'height', 'size', 'alt_text', 'title', 'status'],
    statusOptions: CATEGORY_STATUS_OPTIONS,
    defaultStatus: 'active',
    allowCreate: false,
    standaloneUpload: true,
  },
  site_settings: {
    label: 'Site Settings',
    eyebrow: 'Global configuration',
    description: 'Manage footer texts, contact settings, site title, and legal links.',
    titleField: 'config_key',
    table: ['id', 'config_key', 'group_name', 'language_id'],
    required: ['config_key'],
    fields: ['config_key', 'config_value', 'language_id', 'group_name', 'description'],
  },
  inquiry_submissions: {
    label: 'Yêu Cầu Từ Khách Hàng',
    editLabel: 'Trả lời',
    editorPresentation: 'modal',
    eyebrow: 'Inquiry submissions',
    description: 'Xem và xử lý các yêu cầu báo giá sản phẩm từ người dùng gửi qua form.',
    titleField: 'full_name',
    table: ['id', 'full_name', 'email', 'phone', 'subject', 'message', 'admin_response', 'status', 'created_at'],
    required: ['full_name', 'email', 'message'],
    fields: ['full_name', 'email', 'phone', 'company', 'subject', 'message', 'status', 'admin_response'],
    statusOptions: [
      { value: 'new', label: 'Mới' },
      { value: 'in_progress', label: 'Đang xử lý' },
      { value: 'replied', label: 'Đã trả lời' },
      { value: 'resolved', label: 'Đã giải quyết' },
      { value: 'spam', label: 'Spam' },
    ],
    defaultStatus: 'new',
    previewCard: (record) => ({
      badge: 'Phản hồi',
      title: record.admin_response ? 'Đã trả lời' : 'Chưa trả lời',
      summary: record.admin_response 
        ? `Nội dung: ${record.admin_response}`
        : 'Yêu cầu này chưa có nội dung phản hồi nội bộ.',
      status: record.admin_response ? 'resolved' : 'warning',
    }),
    fieldLabels: {
      full_name: 'Họ và Tên',
      email: 'Email',
      phone: 'Số Điện Thoại',
      company: 'Công Ty / Tổ Chức',
      subject: 'Chủ Đề',
      message: 'Nội Dung Yêu Cầu',
      status: 'Trạng Thái',
      created_at: 'Thời Gian Gửi',
      admin_response: 'Phản Hồi (Nội bộ)',
    },
    placeholders: {
      admin_response: 'Ghi chú nội dung bạn đã trả lời khách hàng hoặc kết quả xử lý...',
    },
    helpText: {
      admin_response: 'Thông tin này hiện chỉ hiển thị trong quản trị để bạn theo dõi lịch sử xử lý yêu cầu.',
    },
  },
  news_posts: {
    label: 'Quản Lý Bài Viết',
    eyebrow: 'Quản trị tin tức',
    description: 'Quản lý bài viết tin tức theo mô hình danh sách + chi tiết, không sử dụng category ở website public.',
    titleField: 'title',
    table: ['id', 'title', 'slug', 'status', 'is_featured', 'published_at', 'created_at'],
    required: ['title', 'slug'],
    fields: [
      'title', 'title_en', 'title_zh',
      'slug',
      'summary', 'summary_en', 'summary_zh',
      'content', 'content_en', 'content_zh',
      'content_json',
      'thumbnail_url', 'image_id', 'author',
      'status', 'is_featured', 'published_at',
      'meta_title', 'meta_title_en', 'meta_title_zh',
      'meta_description', 'meta_description_en', 'meta_description_zh',
      'sort_order',
    ],
    statusOptions: CONTENT_STATUS_OPTIONS,
    defaultStatus: 'draft',
    fieldLabels: {
      title: 'Tiêu Đề (VI)',
      title_en: 'Tiêu Đề (EN)',
      title_zh: 'Tiêu Đề (ZH)',
      slug: 'Slug (URL)',
      summary: 'Tóm Tắt (VI)',
      summary_en: 'Tóm Tắt (EN)',
      summary_zh: 'Tóm Tắt (ZH)',
      content: 'Nội Dung (VI)',
      content_en: 'Nội Dung (EN)',
      content_zh: 'Nội Dung (ZH)',
      content_json: 'Nội Dung (Block Editor)',
      thumbnail_url: 'Ảnh Thumbnail (URL)',
      image_id: 'Ảnh Thumbnail (Media)',
      author: 'Tác Giả',
      status: 'Trạng Thái',
      is_featured: 'Nổi Bật',
      published_at: 'Ngày Xuất Bản',
      meta_title: 'SEO Title (VI)',
      meta_title_en: 'SEO Title (EN)',
      meta_title_zh: 'SEO Title (ZH)',
      meta_description: 'SEO Description (VI)',
      meta_description_en: 'SEO Description (EN)',
      meta_description_zh: 'SEO Description (ZH)',
      sort_order: 'Thứ Tự',
    },
    placeholders: {
      title: 'Nhập tiêu đề bài viết...',
      title_en: 'English article title...',
      title_zh: '中文文章标题...',
      slug: 'tu-dong-tao-tu-tieu-de',
      summary: 'Mô tả ngắn cho bài viết...',
      summary_en: 'Short English summary...',
      summary_zh: '中文摘要...',
    },
  },
  product_categories: {
    label: 'Danh Mục Sản Phẩm',
    eyebrow: 'Product taxonomy',
    description: 'Quản lý danh mục sản phẩm theo cây phân cấp cha/con. Mỗi danh mục có tên, slug, mô tả và ảnh đại diện.',
    titleField: 'name',
    editorPresentation: 'modal',
    table: ['id', 'name', 'parent_name', 'slug', 'sort_order', 'is_active'],
    required: ['name', 'slug'],
    fields: ['name', 'name_en', 'name_zh', 'slug', 'parent_id', 'description', 'description_en', 'description_zh', 'image_url', 'sort_order', 'is_active'],
    relationEntities: {
      parent_id: 'product_categories',
    },
    fieldLabels: {
      name: 'Tên Danh Mục (VI)',
      name_en: 'Tên Danh Mục (EN)',
      name_zh: 'Tên Danh Mục (ZH)',
      slug: 'Slug (URL)',
      parent_id: 'Danh Mục Cha',
      parent_name: 'Thuộc Danh Mục',
      description: 'Mô Tả (VI)',
      description_en: 'Mô Tả (EN)',
      description_zh: 'Mô Tả (ZH)',
      image_url: 'Ảnh Đại Diện (URL)',
      sort_order: 'Thứ Tự Hiển Thị',
      is_active: 'Đang Hoạt Động',
    },
    placeholders: {
      name: 'Ví dụ: Sàn Gỗ',
      name_en: 'Example: Wooden Flooring',
      name_zh: '例如：木地板',
      slug: 'san-go',
      parent_id: 'Để trống nếu là danh mục gốc',
      description: 'Mô tả ngắn về danh mục sản phẩm.',
      image_url: 'https://cdn.example.com/category-thumbnail.jpg',
    },
    helpText: {
      slug: 'Dùng cho URL và lọc sản phẩm. Viết thường, không dấu, dùng dấu gạch ngang.',
      parent_id: 'Chọn danh mục cha để tạo danh mục con. Để trống nếu là danh mục cấp 1.',
      sort_order: 'Dùng 10, 20, 30... để dễ sắp xếp lại sau này.',
    },
    preview: (record) => `/products?category=${record.slug}`,
  },
  products: {
    label: 'Sản Phẩm',
    eyebrow: 'Product catalog',
    description: 'Quản lý sản phẩm: tên, mã SKU, danh mục, giá bán, tồn kho, mô tả, kích thước, chất liệu, màu sắc, ứng dụng, video, catalog PDF.',
    titleField: 'name',
    editorPresentation: 'modal',
    table: ['id', 'image_url', 'name', 'sku', 'original_price', 'sale_price', 'stock_quantity', 'category_id', 'sort_order', 'is_active'],
    required: ['name', 'slug'],
    fields: [
      'name', 'name_en', 'name_zh',
      'slug', 'sku', 'category_id',
      'image_url',
      'gallery_urls',
      'original_price', 'sale_price', 'stock_quantity',
      'short_desc', 'short_desc_en', 'short_desc_zh',
      'full_desc', 'full_desc_en', 'full_desc_zh',
      'size', 'size_en', 'size_zh',
      'material', 'material_en', 'material_zh',
      'color', 'color_en', 'color_zh',
      'use_case', 'use_case_en', 'use_case_zh',
      'video_url', 'catalog_pdf_url',
      'sort_order', 'is_active',
    ],
    cloudinaryAssetFolder: 'products',
    mediaUploadTargetField: 'image_url',
    mediaUploadAccept: 'image/*,video/*,application/pdf',
    fieldLabels: {
      name: 'Tên Sản Phẩm (VI)',
      name_en: 'Tên Sản Phẩm (EN)',
      name_zh: 'Tên Sản Phẩm (ZH)',
      slug: 'Slug (URL)',
      sku: 'Mã Sản Phẩm (SKU)',
      category_id: 'Danh Mục',
      image_url: 'Ảnh Sản Phẩm Gốc (URL)',
      gallery_urls: 'Ảnh Liên Quan Sản Phẩm (mỗi dòng một URL)',
      original_price: 'Giá Gốc',
      sale_price: 'Giá Khuyến Mãi',
      stock_quantity: 'Số Lượng Tồn Kho',
      short_desc: 'Mô Tả Ngắn (VI)',
      short_desc_en: 'Mô Tả Ngắn (EN)',
      short_desc_zh: 'Mô Tả Ngắn (ZH)',
      full_desc: 'Mô Tả Chi Tiết (VI)',
      full_desc_en: 'Mô Tả Chi Tiết (EN)',
      full_desc_zh: 'Mô Tả Chi Tiết (ZH)',
      size: 'Kích Thước (VI)',
      size_en: 'Kích Thước (EN)',
      size_zh: 'Kích Thước (ZH)',
      material: 'Chất Liệu (VI)',
      material_en: 'Chất Liệu (EN)',
      material_zh: 'Chất Liệu (ZH)',
      color: 'Màu Sắc (VI)',
      color_en: 'Màu Sắc (EN)',
      color_zh: 'Màu Sắc (ZH)',
      use_case: 'Ứng Dụng (VI)',
      use_case_en: 'Ứng Dụng (EN)',
      use_case_zh: 'Ứng Dụng (ZH)',
      video_url: 'Video Demo (URL)',
      catalog_pdf_url: 'Catalog PDF (URL)',
      sort_order: 'Thứ Tự',
      is_active: 'Đang Bán',
    },
    placeholders: {
      name: 'Ví dụ: Sàn Gỗ Sồi Tự Nhiên',
      slug: 'san-go-soi-tu-nhien',
      sku: 'FLR-OAK-001',
      image_url: 'Dán link ảnh gốc sản phẩm hoặc upload phía trên.',
      gallery_urls: 'Mỗi dòng là một ảnh liên quan. Upload vào mục này sẽ tự nối thêm URL mới.',
      original_price: 'Ví dụ: 1250000',
      sale_price: 'Ví dụ: 990000',
      stock_quantity: 'Ví dụ: 120',
      short_desc: 'Mô tả ngắn hiển thị trên thẻ sản phẩm.',
      full_desc: 'Mô tả đầy đủ hiển thị trên trang chi tiết sản phẩm.',
      size: 'Ví dụ: 1220 × 150 × 15 mm',
      material: 'Ví dụ: Gỗ Sồi Trắng (Oak)',
      color: 'Ví dụ: Nâu vàng tự nhiên',
      use_case: 'Ví dụ: Phòng ngủ, phòng khách, văn phòng',
      video_url: 'Dán link YouTube/Cloudinary hoặc chọn tệp tải lên.',
      catalog_pdf_url: 'Link file PDF catalog.',
    },
    helpText: {
      sku: 'Mã sản phẩm duy nhất. Ví dụ: OS.01',
      category_id: 'Chọn danh mục chứa sản phẩm này.',
      image_url: 'Đây là ảnh chính/ảnh gốc của sản phẩm, dùng làm ảnh đại diện.',
      gallery_urls: 'Danh sách ảnh liên quan. Có thể dán nhiều URL hoặc upload vào đúng mục này để tự thêm mới.',
      original_price: 'Giá niêm yết/gốc của sản phẩm. FE sẽ ưu tiên dùng trường này khi không có giá khuyến mãi.',
      sale_price: 'Giá bán thực tế khi đang khuyến mãi. Để trống hoặc 0 nếu sản phẩm không giảm giá.',
      stock_quantity: 'Số lượng còn lại trong kho. Hệ thống dùng giá trị này để hiển thị còn hàng/hết hàng và giới hạn số lượng mua.',
      video_url: 'Link YouTube embed hoặc link MP4 tải lên. Để trống nếu không có.',
      catalog_pdf_url: 'Link file PDF catalog tải lên hoặc dán URL.',
    },
    relationEntities: {
      category_id: 'product_categories',
    },
    preview: (record) => `/products/${record.slug}`,
    featuredTableFields: ['image_url', 'sale_price', 'stock_quantity', 'is_active'],
  },
  users: {
    label: 'Quản Lý Tài Khoản',
    eyebrow: 'User accounts management',
    description: 'Quản lý tài khoản người dùng đã đăng ký: email, tên đăng nhập, số điện thoại, avatar, phân quyền, trạng thái kích hoạt và đặt lại mật khẩu an toàn từ trang admin.',
    titleField: 'email',
    editorPresentation: 'modal',
    table: ['id', 'email', 'username', 'phone', 'role', 'is_active', 'last_login_at', 'created_at'],
    required: ['email'],
    fields: ['email', 'username', 'phone', 'avatar_url', 'role', 'password', 'is_active'],
    fieldLabels: {
      email: 'Email',
      username: 'Tên đăng nhập',
      phone: 'Số điện thoại',
      avatar_url: 'Avatar / Ảnh đại diện',
      role: 'Phân quyền',
      password: 'Mật khẩu',
      is_active: 'Đang hoạt động',
      last_login_at: 'Đăng nhập gần nhất',
      created_at: 'Ngày tạo',
    },
    placeholders: {
      email: 'user@example.com',
      username: 'ten_dang_nhap',
      phone: '0987654321',
      avatar_url: 'https://example.com/avatar.jpg',
      password: 'Tối thiểu 6 ký tự',
    },
    selectOptions: {
      role: [
        { value: 'user', label: 'User' },
        { value: 'admin', label: 'Admin' },
      ],
    },
    helpText: {
      avatar_url: 'Dán URL ảnh đại diện để hiển thị trong trang chi tiết tài khoản.',
      role: 'Chọn quyền truy cập của tài khoản. Có thể mở rộng thêm cấp quyền khác về sau.',
      password: 'Khi tạo tài khoản bắt buộc nhập mật khẩu. Khi chỉnh sửa, để trống nếu không muốn đổi mật khẩu hiện tại.',
      is_active: 'Tắt trạng thái này để khóa tài khoản đăng nhập của người dùng.',
      username: 'Nên giữ duy nhất để tránh trùng lặp khi quản lý tài khoản.',
    },
    featuredTableFields: ['email', 'role', 'is_active'],
  },
  orders: {
    label: 'Quản Lý Đơn Hàng',
    editLabel: 'Cập nhật trạng thái',
    eyebrow: 'COD order management',
    description: 'Theo dõi toàn bộ đơn hàng COD, cập nhật trạng thái xử lý và trạng thái thanh toán trực tiếp từ trang quản trị.',
    titleField: 'code',
    editorPresentation: 'modal',
    table: [
      'id',
      'code',
      'customer_name',
      'customer_phone',
      'payment_method_label',
      'status_label',
      'payment_status_label',
      'total_amount',
      'placed_at',
    ],
    required: [],
    fields: ['status', 'payment_status', 'note'],
    statusOptions: [
      { value: 'pending_confirmation', label: 'Chờ xác nhận' },
      { value: 'confirmed', label: 'Đã xác nhận' },
      { value: 'processing', label: 'Đang chuẩn bị hàng' },
      { value: 'shipping', label: 'Đang giao hàng' },
      { value: 'delivered', label: 'Đã giao hàng' },
      { value: 'cancelled', label: 'Đã hủy' },
    ],
    selectOptions: {
      payment_status: [
        { value: 'unpaid', label: 'Chưa thanh toán' },
        { value: 'paid', label: 'Đã thanh toán' },
      ],
    },
    fieldLabels: {
      code: 'Mã đơn hàng',
      customer_name: 'Khách hàng',
      customer_phone: 'Số điện thoại',
      customer_email: 'Email',
      shipping_address: 'Địa chỉ giao hàng',
      payment_method: 'Phương thức thanh toán',
      payment_method_label: 'Phương thức thanh toán',
      payment_status: 'Trạng thái thanh toán',
      payment_status_label: 'Thanh toán',
      status: 'Trạng thái đơn hàng',
      status_label: 'Trạng thái đơn hàng',
      subtotal_amount: 'Tạm tính',
      shipping_fee: 'Phí vận chuyển',
      discount_amount: 'Giảm giá',
      total_amount: 'Tổng thanh toán',
      currency: 'Tiền tệ',
      item_count: 'Số lượng sản phẩm',
      placed_at: 'Thời điểm đặt hàng',
      created_at: 'Ngày tạo',
      updated_at: 'Cập nhật gần nhất',
      note: 'Ghi chú đơn hàng',
    },
    placeholders: {
      note: 'Ví dụ: khách yêu cầu giao giờ hành chính, xác nhận qua Zalo...',
    },
    helpText: {
      status: 'Chỉ nên chuyển tuần tự theo quy trình COD: chờ xác nhận → đã xác nhận → chuẩn bị hàng → đang giao → đã giao.',
      payment_status: 'COD thường để “Chưa thanh toán” cho đến khi đơn được giao và thu tiền thành công.',
      note: 'Ghi chú này giúp đội vận hành theo dõi các yêu cầu đặc biệt của khách hoặc diễn biến xử lý đơn.',
    },
    featuredTableFields: ['code', 'status_label', 'payment_status_label'],
    allowCreate: false,
  },
}

export const ADMIN_SECTION_GROUPS = [
  { title: 'TỔNG QUAN', items: [{ key: 'dashboard', label: 'Bảng Điều Khiển' }] },
  {
    title: 'CẤU HÌNH HỆ THỐNG',
    items: [
      { key: 'navigation', label: 'Menu Điều Hướng' },
      { key: 'site_settings', label: 'Cài Đặt Website (Tên, Logo, Slogan)' },
      { key: 'banners', label: 'Banner & Slider' },
      { key: 'users', label: 'Quản Lý Tài Khoản' },
    ],
  },
  {
    title: 'GIỚI THIỆU CÔNG TY (ABOUT)',
    items: [{ key: 'content_block_items', label: 'Quản lý toàn bộ trang Giới thiệu' }],
  },
  {
    title: 'NĂNG LỰC',
    items: [
      {
        key: 'capability_settings',
        label: 'Cấu Hình Trang Năng Lực',
        description: 'Quản lý hero, tổng quan nhà máy, gallery, chỉ số và năng lực sản xuất.',
      },
      {
        key: 'honor_categories',
        label: 'Danh Mục Năng Lực',
        description: 'Thêm, sửa, xóa danh mục năng lực; quản lý phân cấp, trạng thái và thứ tự hiển thị.',
      },
      {
        key: 'honors',
        label: 'Mục Năng Lực / Chứng Nhận',
        description: 'Thêm, sửa, xóa các mục chứng nhận, danh hiệu và nội dung hiển thị trong trang năng lực.',
      },
      {
        key: 'media_assets',
        label: 'Thư Viện Ảnh Nhà Máy',
        description: 'Quản lý ảnh dùng cho nhà máy, công nghệ sản xuất, chứng nhận và toàn bộ media liên quan.',
      },
    ],
  },
  {
    title: 'SẢN PHẨM',
    items: [
      { key: 'products', label: 'Danh Sách Sản Phẩm' },
      { key: 'product_categories', label: 'Danh Mục Sản Phẩm' },
      { key: 'videos', label: 'Video Sản Phẩm' },
    ],
  },
  {
    title: 'ĐƠN HÀNG',
    items: [{ key: 'orders', label: 'Quản Lý Đơn Hàng COD' }],
  },
  {
    title: 'DỰ ÁN',
    items: [{ key: 'projects', label: 'Quản Lý Dự Án' }],
  },
  {
    title: 'LIÊN HỆ',
    items: [
      { key: 'contacts', label: 'Thông Tin Liên Hệ' },
      { key: 'inquiry_submissions', label: 'Phản Hồi Từ Form' },
    ],
  },
  {
    title: 'TIN TỨC',
    items: [
      {
        key: 'news_posts',
        label: 'Quản Lý Bài Viết',
      },
    ],
  },
]

function flattenSectionItems(items, collector = []) {
  for (const item of items || []) {
    collector.push(item)
    if (Array.isArray(item.children) && item.children.length) {
      flattenSectionItems(item.children, collector)
    }
  }
  return collector
}

export const ADMIN_SECTION_INDEX = Object.fromEntries(ADMIN_SECTION_GROUPS.flatMap((group) => flattenSectionItems(group.items)).map((item) => [item.key, item]))

