export const DEFAULT_STATUS_OPTIONS = [
  { value: 'published', label: 'Published' },
  { value: 'draft', label: 'Draft' },
  { value: 'archived', label: 'Archived' },
  { value: 'active', label: 'Active' },
  { value: 'inactive', label: 'Inactive' },
  { value: 'new', label: 'New' },
  { value: 'in_progress', label: 'In Progress' },
  { value: 'resolved', label: 'Resolved' },
]

export const CATEGORY_STATUS_OPTIONS = [
  { value: 'active', label: 'Active' },
  { value: 'inactive', label: 'Inactive' },
]

export const CONTENT_STATUS_OPTIONS = [
  { value: 'draft', label: 'Draft' },
  { value: 'published', label: 'Published' },
  { value: 'archived', label: 'Archived' },
]

export const ENTITY_MANAGER_CONFIGS = {
  pages: {
    label: 'admin.entities.pages.label',
    eyebrow: 'admin.entities.pages.eyebrow',
    description: 'admin.entities.pages.description',
    titleField: 'title',
    editorPresentation: 'modal',
    table: ['id', 'title', 'slug', 'page_type', 'status', 'language_id', 'sort_order'],
    required: ['slug', 'language_id'],
    fields: ['slug', 'title', 'summary', 'body', 'page_type', 'language_id', 'parent_id', 'status', 'meta_title', 'meta_description', 'sort_order'],
    statusOptions: CONTENT_STATUS_OPTIONS,
    defaultStatus: 'draft',
    preview: (record) => `/${record.slug}`,
    fieldLabels: {
      slug: 'Đường dẫn (Slug)',
      title: 'Tiêu đề trang',
      summary: 'Tóm tắt ngắn',
      body: 'Nội dung chi tiết',
      page_type: 'Loại trang',
      language_id: 'Ngôn ngữ',
      parent_id: 'Trang cha',
      status: 'Trạng thái xuất bản',
      meta_title: 'SEO Meta Title',
      meta_description: 'SEO Meta Description',
      title_en: 'Ten Du An (EN)',
      title_zh: 'Ten Du An (ZH)',
      summary_en: 'Mo Ta Ngan (EN)',
      summary_zh: 'Mo Ta Ngan (ZH)',
      body_en: 'Mo Ta Chi Tiet (EN)',
      body_zh: 'Mo Ta Chi Tiet (ZH)',
      location_en: 'Dia Diem (EN)',
      location_zh: 'Dia Diem (ZH)',
      meta_title_en: 'SEO Title (EN)',
      meta_title_zh: 'SEO Title (ZH)',
      meta_description_en: 'SEO Description (EN)',
      meta_description_zh: 'SEO Description (ZH)',
      sort_order: 'Thứ tự hiển thị',
    },
    placeholders: {
      title_en: 'Example: Hengtong Building',
      title_zh: 'Chinese project title...',
      slug: 'hengtong-building',
      summary_en: 'Short English project summary...',
      summary_zh: 'Chinese project summary...',
      body_en: 'Detailed English project content...',
      body_zh: 'Detailed Chinese project content...',
      location_en: 'Example: Guangzhou, China',
      location_zh: 'Example: Guangzhou, China',
      title_en: 'Example: Hengtong Building',
      title_zh: 'Chinese project title...',
      slug: 'hengtong-building',
      summary_en: 'Short English project summary...',
      summary_zh: 'Chinese project summary...',
      body_en: 'Detailed English project content...',
      body_zh: 'Detailed Chinese project content...',
      location_en: 'Example: Guangzhou, China',
      location_zh: 'Example: Guangzhou, China',
      slug: 'Ví dụ: about',
      title: 'Ví dụ: Giới thiệu công ty',
      summary: 'Tóm tắt ngắn gọn của trang dùng cho SEO và API công khai.',
      body: 'Nội dung chi tiết (không bắt buộc nếu dùng các khối nội dung).',
      page_type: 'Ví dụ: about',
      meta_title: 'Tiêu đề SEO hiển thị trên tab trình duyệt.',
      meta_description: 'Mô tả SEO ngắn gọn cho trang.',
    },
    helpText: {
      slug: 'Đối với trang Giới thiệu hiện tại, hãy giữ nguyên slug `about`. Không tạo thêm các hàng riêng biệt cho từng phần như introduction hay vision.',
      page_type: 'Sử dụng tên nhóm ổn định như about, legal hoặc contact.',
      parent_id: 'Thường để trống cho các trang cấp cao nhất.',
      status: 'Chỉ các trang được "Published" mới hiển thị trên website.',
      meta_title: 'Khuyên dùng cho SEO. Nếu để trống sẽ dùng tiêu đề trang.',
      meta_description: 'Khuyên dùng cho SEO và xem trước trên mạng xã hội.',
      sort_order: 'Dùng 10, 20, 30... để dễ dàng sắp xếp lại thứ tự sau này.',
    },
  },
  page_sections: {
    label: 'Các Phần Trang',
    eyebrow: 'Cấu trúc các phần của trang',
    description: 'Quản lý các phần cấu trúc bên trong một trang CMS. Ví dụ với trang Giới thiệu, bảng này chứa các phần: Hero, Giới thiệu công ty, Tầm nhìn & Sứ mệnh, Sơ đồ tổ chức, Giá trị cốt lõi, Lịch sử phát triển, Ban lãnh đạo.',
    titleField: 'title',
    editorPresentation: 'modal',
    hideMediaGallery: true,
    table: ['id', 'page_id', 'title', 'anchor', 'section_type', 'sort_order'],
    required: ['page_id'],
    fields: ['page_id', 'anchor', 'title', 'content', 'image_id', 'section_type', 'sort_order'],
    preview: (record) => {
      if (record.preview_href) {
        return record.preview_href
      }

      if (record.page_slug === 'about') {
        const aboutRouteMap = {
          hero: '/about/company-introduction#page1',
          company_introduction: '/about/company-introduction#page2',
          chairman_speech: '/about/chairman-speech#page3',
          organization_chart: '/about/organization-chart#page4',
          corporate_culture: '/about/corporate-culture#page5',
          development_course: '/about/development-course#page6',
          leadership_care: '/about/leadership-care#page7',
        }
        return aboutRouteMap[record.anchor] || '/about/company-introduction#page1'
      }

      if (record.page_slug) {
        return `/${record.page_slug}${record.anchor ? `#${record.anchor}` : ''}`
      }

      return ''
    },
    fields: ['title', 'content', 'image_id', 'sort_order'],
    fieldLabels: {
      title: 'Tên mục hiển thị',
      content: 'Ghi chú (Nội bộ)',
      image_id: 'Ảnh đại diện/Ảnh nền',
      sort_order: 'Thứ tự',
    },
    helpText: {
      page_id: 'Chọn trang cha mà phần này thuộc về. Với trang Giới thiệu, tất cả các phần nên thuộc về trang `about`.',
      anchor: 'Mã kỹ thuật dùng để link chính xác đến phần đó trên web. KHÔNG đổi khi không cần thiết.',
      image_id: 'Ảnh nền hoặc ảnh đại diện cho phần này.',
      section_type: 'Phân loại loại mục để FE xử lý style tương ứng.',
      sort_order: 'Dùng 10, 20, 30... để kiểm soát thứ tự từ trên xuống dưới.',
      content: 'Dùng như ghi chú nội bộ để người quản trị biết phần này điều khiển nội dung nào.',
    },
  },
  content_blocks: {
    label: 'Khối Nội Dung',
    eyebrow: 'Các khối nội dung CMS',
    description: 'Quản lý các khối nội dung lớn gắn với một trang. Đối với trang Giới thiệu, các khối nên gắn với Loai đối tượng = page và ID bản ghi = id của trang `about` (thường là 1).',
    recordDisplayName: (record) => {
      const translations = {
        'hero_summary': '1. Tên công ty & Slogan',
        'hero_nav': '2. Menu điều hướng trang',
        'intro_media': '3. Hình ảnh/Video giới thiệu',
        'intro_video': '4. Nút bấm xem Video',
        'intro_paragraphs': '5. Các đoạn văn giới thiệu',
        'speech_profile': '6. Ảnh chân dung Lãnh đạo',
        'speech_body': '7. Văn bản Tầm nhìn & Sứ mệnh',
        'speech_signature': '8. Chữ ký Lãnh đạo',
        'org_chart_image': '9. Sơ đồ tổ chức',
        'culture_values': '10. Giá trị cốt lõi',
        'culture_slogan': '11. Slogan',
        'timeline': '12. Lịch sử phát triển',
        'leadership_care_gallery': '13. Ban lãnh đạo (Album)',
      }
      const rawKey = String(record?.block_key || record?.title || '').toLowerCase().trim();
      // Try to find a match by comparing lowercase keys
      const matchedKey = Object.keys(translations).find(k => k.toLowerCase() === rawKey);
      return matchedKey ? translations[matchedKey] : (record?.block_key || record?.title || '');
    },
    table: ['id', 'block_key', 'block_type', 'sort_order'],
    required: ['entity_id', 'block_key', 'block_type'],
    fields: ['entity_id', 'block_key', 'block_type', 'title', 'sort_order'],
    fieldLabels: {
      entity_type: 'Loại trang',
      entity_id: 'ID Trang',
      language_id: 'Ngôn ngữ',
      block_key: 'Mã định danh nhóm',
      title: 'Tiêu đề nhóm (Nếu có)',
      subtitle: 'Phụ đề nhóm',
      content: 'Mô tả nội bộ',
      block_type: 'Loại hiển thị',
      sort_order: 'Thứ tự ưu tiên',
    },
    relationEntities: {
      entity_id: 'pages',
    },
    fieldLabels: {
      entity_type: 'Loại thực thể',
      entity_id: 'ID bản ghi trang',
      language_id: 'Ngôn ngữ',
      block_key: 'Mã định danh khối',
      title: 'Tiêu đề khối',
      subtitle: 'Phụ đề khối',
      content: 'Nội dung khối',
      block_type: 'Loại khối',
      sort_order: 'Thứ tự hiển thị',
    },
    placeholders: {
      entity_type: 'Ví dụ: page',
      entity_id: 'ID của bản ghi trang liên quan',
      block_key: 'Ví dụ: intro_paragraphs',
      title: 'Tiêu đề khối (tùy chọn)',
      subtitle: 'Phụ đề khối (tùy chọn)',
      content: 'Nội dung văn bản dài (tùy chọn)',
      block_type: 'Ví dụ: rich_text_list, timeline, logo_grid',
    },
    helpText: {
      entity_type: 'Đối với trang Giới thiệu, hãy khóa giá trị này là `page`.',
      entity_id: 'Nhập ID của bản ghi trang mà khối này thuộc về.',
      block_key: 'Mã định danh ổn định. Ví dụ: intro_paragraphs (giới thiệu), speech_body (tầm nhìn), culture_values/culture_slogan (giá trị & slogan), timeline (lịch sử), leadership_profiles (lãnh đạo).',
      block_type: 'Phân loại loại khối: rich_text_list, media_profile, timeline, carousel_cards.',
      sort_order: 'Dùng 10, 20, 30... để kiểm soát thứ tự khối trong cùng một trang.',
    },
  },
  content_block_items: {
    label: 'Mục Chi Tiết (Khối)',
    eyebrow: 'Chi tiết bên trong khối nội dung',
    description: 'Quản lý các mục con bên trong mỗi khối nội dung, ví dụ: các đoạn văn, mốc lịch sử, hồ sơ ban lãnh đạo, logo đối tác.',
    titleField: 'title',
    editorPresentation: 'modal',
    hideMediaGallery: true,
    recordDisplayName: (record) => {
      const translations = {
        'hero_summary': '1. Tên công ty & Slogan',
        'intro_paragraphs': '5. Văn bản giới thiệu',
        'cover_image': 'Ảnh bìa/Ảnh nền',
        'paragraph_1': 'Đoạn văn số 1',
        'paragraph_2': 'Đoạn văn số 2',
        'paragraph_3': 'Đoạn văn số 3',
        'portrait': 'Ảnh chân dung lãnh đạo',
        'sign_name': 'Họ tên lãnh đạo',
        'sign_title': 'Chức danh lãnh đạo',
        'visit_1': 'Mục lịch sử/Lãnh đạo 1',
        'milestone_1': 'Mốc lịch sử 1',
        'milestone_2': 'Mốc lịch sử 2',
      }
      const rawTitle = record?.title || '';
      const rawKey = String(record?.item_key || '').toLowerCase().trim();
      return rawTitle || translations[rawKey] || rawKey || `#${record?.id}`;
    },
    table: ['id', 'block_id', 'title', 'item_key', 'sort_order'],
    required: ['block_id', 'item_key'],
    fields: [
      'block_id', 'item_key',
      'title', 'title_en', 'title_zh',
      'subtitle', 'subtitle_en', 'subtitle_zh',
      'content', 'content_en', 'content_zh',
      'link', 'image_id', 'sort_order',
    ],
    fieldLabels: {
      block_id: 'Thuộc nhóm nội dung',
      item_key: 'Mã mục (item_key)',
      title: 'Tên mục (Để bạn dễ tìm)',
      subtitle: 'Phụ đề / Chức vụ / Năm-Tháng',
      content: 'Nội dung chi tiết / Văn bản',
      link: 'Liên kết / URL',
      image_id: 'Hình ảnh / Logo / Sơ đồ',
      sort_order: 'Thứ tự hiển thị (10, 20...)',
    },
    optionLabel: (option, field) => {
      if (field === 'block_id') {
        const translations = {
          'About Hero Summary': '1. Tên công ty & Slogan',
          'About Navigation Tabs': '2. Menu điều hướng trang',
          'Company Introduction Media': '3. Hình ảnh/Video giới thiệu',
          'Company Introduction Text': '4. Nội dung bài viết giới thiệu',
          'Chairman Portrait': '5. Ảnh chân dung lãnh đạo',
          'Chairman\'s Speech Text': '6. Văn bản Tầm nhìn & Sứ mệnh',
          'Chairman Signature': '7. Chữ ký lãnh đạo',
          'Organization Chart': '8. Sơ đồ tổ chức',
          'Corporate Culture': '9. Giá trị cốt lõi',
          'Development Course Timeline': '10. Lịch sử phát triển',
          'Leadership Care Gallery': '11. Danh sách ban lãnh đạo',
        }
        const key = option.title || option.name || ''
        return translations[key] || `#${option.id} - ${key}`
      }
      return `#${option.id} - ${option.title || option.name || option.slug}`
    },
    placeholders: {
      item_key: 'Ví dụ: paragraph_1, vision, mission, value_1, milestone_1, leader_1',
      title: 'Ví dụ: Nguyễn Văn A hoặc Thành lập công ty',
      subtitle: 'Ví dụ: Giám đốc Điều hành hoặc 2024-01 (timeline)',
      content: 'Nhập nội dung văn bản cho mục này.',
      link: 'https://example.com hoặc /internal-path',
    },
    helpText: {
      block_id: 'Chọn khối cha trước. Các mục sẽ luôn hiển thị bên trong khối này.',
      item_key: 'Mã kỹ thuật định danh mục. Bắt buộc theo chuẩn từng block (ví dụ: vision/mission, value_1, milestone_1, leader_1...).',
      subtitle: 'Dùng cho chức vụ ở Ban lãnh đạo. Riêng timeline, nhập Năm/Tháng dạng 2024 hoặc 2024-01.',
      image_id: 'Ảnh đại diện cho cá nhân (Ban lãnh đạo), ảnh mốc lịch sử hoặc logo đối tác.',
      link: 'Dùng cho mục cần gắn URL ngoài hoặc đường dẫn nội bộ.',
      sort_order: 'Dùng 10, 20, 30... để sắp xếp thứ tự các mục bên trong khối.',
    },
  },
  banners: {
    label: 'admin.entities.banners.label',
    eyebrow: 'admin.entities.banners.eyebrow',
    description: 'admin.entities.banners.description',
    titleField: 'title',
    table: ['id', 'title', 'banner_type', 'placement', 'sort_order', 'is_active'],
    required: ['placement'],
    fields: ['title', 'subtitle', 'body', 'image_id', 'focus_x', 'focus_y', 'link', 'button_text', 'banner_type', 'placement', 'sort_order', 'is_active'],
    statusOptions: [
      { value: 'active', label: 'Active' },
      { value: 'inactive', label: 'Inactive' },
    ],
    selectOptions: {
      banner_type: [
        { value: 'hero', label: 'Hero (Main Slider)' },
        { value: 'cta', label: 'CTA (Call to Action)' },
        { value: 'secondary', label: 'Secondary Banner' },
        { value: 'video_bg', label: 'Video Background' },
      ],
      placement: [
        { value: 'home', label: 'Trang chủ (Home)' },
        { value: 'about', label: 'Giới thiệu (About)' },
        { value: 'products', label: 'Sản phẩm (Products)' },
        { value: 'news', label: 'Tin tức (News)' },
        { value: 'contact', label: 'Liên hệ (Contact)' },
        { value: 'global', label: 'Toàn trang (Global)' },
      ],
    },
    defaultStatus: 'active',
    previewMediaField: 'image_id',
    mediaUploadTargetField: 'image_id',
    mediaUploadAccept: 'image/*,video/*',
    cloudinaryAssetFolder: 'banner',
    fieldLabels: {
      title: 'admin.entities.banners.fields.title',
      subtitle: 'admin.entities.banners.fields.subtitle',
      body: 'admin.entities.banners.fields.body',
      image_id: 'admin.entities.banners.fields.image_id',
      focus_x: 'admin.entities.banners.fields.focus_x',
      focus_y: 'admin.entities.banners.fields.focus_y',
      link: 'admin.entities.banners.fields.link',
      button_text: 'admin.entities.banners.fields.button_text',
      banner_type: 'admin.entities.banners.fields.banner_type',
      placement: 'admin.entities.banners.fields.placement',
      language_id: 'admin.entities.banners.fields.language_id',
      sort_order: 'admin.entities.banners.fields.sort_order',
      is_active: 'admin.entities.banners.fields.is_active',
    },
    placeholders: {
      title: 'Ví dụ: Chào mừng đến với China Decor',
      subtitle: 'Giải pháp nội thất cao cấp',
      body: 'Nhập mô tả ngắn cho banner này.',
      link: '/gioi-thieu hoặc https://example.com',
      button_text: 'Tìm hiểu thêm',
      placement: 'Chọn trang mà banner sẽ xuất hiện',
    },
    helpText: {
      image_id: 'Tải ảnh (JPG, PNG, WebP) hoặc video (MP4, WebM) dùng làm nền banner.',
      focus_x: 'Điểm lấy nét theo chiều ngang cho ảnh crop (0 đến 100).',
      focus_y: 'Điểm lấy nét theo chiều dọc cho ảnh crop (0 đến 100).',
      banner_type: 'Hero = slider trang chủ, CTA = thẻ quảng bá, Section/Page/Footer = vị trí phụ.',
      placement: 'Chọn chính xác trang mà bạn muốn banner này hiển thị.',
      link: 'URL sẽ mở khi người dùng nhấp vào banner hoặc nút CTA.',
      button_text: 'Nội dung hiển thị trên nút CTA (nếu có).',
      is_active: 'Chỉ banner đang bật mới hiển thị ở trang public.',
    },
    featuredTableFields: ['image_id', 'banner_type', 'placement', 'is_active'],
  },
  project_categories: {
    label: 'admin.entities.project_categories.label',
    eyebrow: 'admin.entities.project_categories.eyebrow',
    description: 'admin.entities.project_categories.description',
    titleField: 'name',
    pageSize: 25,
    table: ['id', 'name', 'slug', 'status', 'sort_order'],
    required: ['name', 'slug'],
    fields: ['name', 'slug', 'description', 'parent_id', 'sort_order', 'status'],
    statusOptions: CATEGORY_STATUS_OPTIONS,
    defaultStatus: 'active',
    preview: (record) => `/project_list/${record.id}.html`,
    fieldLabels: {
      name: 'admin.entities.project_categories.fields.name',
      slug: 'admin.entities.project_categories.fields.slug',
      description: 'admin.entities.project_categories.fields.description',
      parent_id: 'admin.entities.project_categories.fields.parent_id',
      sort_order: 'admin.entities.project_categories.fields.sort_order',
      status: 'admin.entities.project_categories.fields.status',
    },
    placeholders: {
      name: 'Ví dụ: Khách Sạn 5 Sao',
      slug: 'khach-san-5-sao',
      description: 'Mô tả ngắn hiển thị trên banner hoặc metadata danh mục.',
    },
    helpText: {
      slug: 'Dùng cho tên chuẩn của taxonomy quản trị/dự án. Route public cũ hiện vẫn sử dụng category id dạng số.',
      sort_order: 'Kiểm soát thứ tự danh mục trong hero slider và sidebar của Project Case.',
      status: 'Chỉ danh mục đang hoạt động mới được public API trả ra.',
    },
  },
  projects: {
    label: 'admin.entities.projects.label',
    eyebrow: 'admin.entities.projects.eyebrow',
    description: 'admin.entities.projects.description',
    titleField: 'title',
    editorPresentation: 'modal',
    table: ['id', 'title', 'location', 'image_id', 'status'],
    required: ['title', 'slug', 'language_id'],
    fields: [
      'title', 'title_en', 'title_zh',
      'slug',
      'location', 'location_en', 'location_zh',
      'summary', 'summary_en', 'summary_zh',
      'body', 'body_en', 'body_zh',
      'image_id', 'hero_image_id',
      'category_id', 'project_year',
      'language_id', 'status',
      'meta_title', 'meta_title_en', 'meta_title_zh',
      'meta_description', 'meta_description_en', 'meta_description_zh',
    ],
    defaultValues: {
      language_id: 1,
      status: 'published',
    },
    relationEntities: {
      category_id: 'project_categories',
      language_id: 'languages',
    },
    mediaUploadTargetField: 'image_id',
    mediaUploadAccept: 'image/*',
    statusOptions: CONTENT_STATUS_OPTIONS,
    defaultStatus: 'published',
    preview: (record) => `/project/${record.slug}`,
    fieldLabels: {
      title: 'admin.entities.projects.fields.title',
      slug: 'admin.entities.projects.fields.slug',
      category_id: 'admin.entities.projects.fields.category_id',
      summary: 'admin.entities.projects.fields.summary',
      body: 'admin.entities.projects.fields.body',
      location: 'admin.entities.projects.fields.location',
      project_year: 'admin.entities.projects.fields.project_year',
      image_id: 'admin.entities.projects.fields.image_id',
      hero_image_id: 'admin.entities.projects.fields.hero_image_id',
      language_id: 'admin.entities.projects.fields.language_id',
      status: 'admin.entities.projects.fields.status',
      meta_title: 'admin.entities.projects.fields.meta_title',
      meta_description: 'admin.entities.projects.fields.meta_description',
      title_en: 'Ten Du An (EN)',
      title_zh: 'Ten Du An (ZH)',
      summary_en: 'Mo Ta Ngan (EN)',
      summary_zh: 'Mo Ta Ngan (ZH)',
      body_en: 'Mo Ta Chi Tiet (EN)',
      body_zh: 'Mo Ta Chi Tiet (ZH)',
      location_en: 'Dia Diem (EN)',
      location_zh: 'Dia Diem (ZH)',
      meta_title_en: 'SEO Title (EN)',
      meta_title_zh: 'SEO Title (ZH)',
      meta_description_en: 'SEO Description (EN)',
      meta_description_zh: 'SEO Description (ZH)',
    },
    placeholders: {
      title_en: 'Example: Hengtong Building',
      title_zh: 'Chinese project title...',
      slug: 'hengtong-building',
      summary_en: 'Short English project summary...',
      summary_zh: 'Chinese project summary...',
      body_en: 'Detailed English project content...',
      body_zh: 'Detailed Chinese project content...',
      location_en: 'Example: Guangzhou, China',
      location_zh: 'Example: Guangzhou, China',
      title: 'Ví dụ: Hengtong Building',
      summary: 'Nhập mô tả ngắn cho dự án.',
      body: 'Nhập mô tả chi tiết cho dự án nếu cần hiển thị ở trang chi tiết.',
      location: 'Ví dụ: Quảng Châu, Trung Quốc',
    },
    helpText: {
      title: 'Tên hiển thị chính của dự án.',
      summary: 'Đây là phần mô tả chính theo requirement.',
      body: 'Có thể dùng để lưu nội dung mô tả dài hơn cho trang chi tiết.',
      location: 'Địa điểm thực hiện dự án.',
      image_id: 'Chọn ảnh đại diện chính cho dự án. Nếu cần nhiều ảnh, dùng mục Hình Ảnh Dự Án ở sidebar.',
    },
  },
  project_category_items: {
    label: 'admin.entities.project_category_items.label',
    eyebrow: 'admin.entities.project_category_items.eyebrow',
    description: 'admin.entities.project_category_items.description',
    titleField: 'anchor',
    pageSize: 25,
    table: ['id', 'category_id', 'project_id', 'anchor', 'sort_order', 'layout_variant', 'is_featured'],
    required: ['category_id', 'project_id', 'anchor', 'sort_order'],
    fields: ['category_id', 'project_id', 'sort_order', 'anchor', 'is_featured', 'layout_variant'],
    preview: (record) => `/project_list/${record.category_id}.html#${record.anchor}`,
    fieldLabels: {
      category_id: 'admin.entities.project_category_items.fields.category_id',
      project_id: 'admin.entities.project_category_items.fields.project_id',
      sort_order: 'admin.entities.project_category_items.fields.sort_order',
      anchor: 'admin.entities.project_category_items.fields.anchor',
      is_featured: 'admin.entities.project_category_items.fields.is_featured',
      layout_variant: 'admin.entities.project_category_items.fields.layout_variant',
    },
    placeholders: {
      anchor: 'Ví dụ: ctn2',
      layout_variant: 'feature hoặc standard',
    },
    helpText: {
      category_id: 'Bắt buộc. Danh mục sở hữu section Project Case này.',
      project_id: 'Bắt buộc. Mỗi dự án chỉ nên xuất hiện một lần trong cùng một danh mục.',
      sort_order: 'Bắt buộc. Public API sẽ sắp xếp case theo giá trị này.',
      anchor: 'Bắt buộc. Phải là duy nhất trong danh mục đã chọn. Nên giữ pattern ctnX cũ để tương thích.',
      layout_variant: 'Frontend hiện dùng feature và standard. Chỉ đổi giá trị khi frontend đã được cập nhật tương ứng.',
    },
    relationEntities: {
      category_id: 'project_categories',
      project_id: 'projects',
    },
  },
  project_products: {
    label: 'admin.entities.project_products.label',
    eyebrow: 'admin.entities.project_products.eyebrow',
    description: 'admin.entities.project_products.description',
    titleField: 'id',
    pageSize: 25,
    table: ['id', 'project_id', 'product_id', 'sort_order', 'note'],
    required: ['project_id', 'product_id'],
    fields: ['project_id', 'product_id', 'sort_order', 'note'],
    preview: () => '',
    fieldLabels: {
      project_id: 'admin.entities.project_products.fields.project_id',
      product_id: 'admin.entities.project_products.fields.product_id',
      sort_order: 'admin.entities.project_products.fields.sort_order',
      note: 'admin.entities.project_products.fields.note',
    },
    placeholders: {
      note: 'Ví dụ: Dùng cho khu vực sảnh chính, vách trang trí, trần hành lang...',
    },
    helpText: {
      project_id: 'Chọn dự án cần gắn sản phẩm.',
      product_id: 'Chọn sản phẩm thực tế đã sử dụng trong dự án này.',
      sort_order: 'Dùng 10, 20, 30... để kiểm soát thứ tự card ở trang chi tiết dự án.',
      note: 'Ghi chú ngắn để mô tả ngữ cảnh ứng dụng của sản phẩm trong công trình.',
    },
    relationEntities: {
      project_id: 'projects',
      product_id: 'products',
    },
  },
  entity_media: {
    label: 'admin.entities.entity_media.label',
    eyebrow: 'admin.entities.entity_media.eyebrow',
    description: 'admin.entities.entity_media.description',
    titleField: 'group_name',
    pageSize: 25,
    table: ['id', 'entity_type', 'entity_id', 'group_name', 'media_id', 'sort_order'],
    required: ['entity_type', 'entity_id', 'media_id', 'group_name', 'sort_order'],
    fields: ['entity_type', 'entity_id', 'media_id', 'group_name', 'sort_order', 'caption'],
    defaultValues: {
      entity_type: 'project_category',
      group_name: 'hero_desktop',
    },
    selectOptions: {
      entity_type: [
        { value: 'project_category', label: 'Danh mục dự án' },
        { value: 'project', label: 'Dự án' },
      ],
      group_name: [
        { value: 'hero_desktop', label: 'Hero desktop' },
        { value: 'hero_mobile', label: 'Hero mobile' },
        { value: 'left_gallery', label: 'Gallery trái' },
        { value: 'right_gallery', label: 'Gallery phải' },
      ],
    },
    selectOptionsByEntityType: {
      group_name: {
        project_category: [
          { value: 'hero_desktop', label: 'Hero desktop' },
          { value: 'hero_mobile', label: 'Hero mobile' },
        ],
        project: [
          { value: 'left_gallery', label: 'Gallery trái' },
          { value: 'right_gallery', label: 'Gallery phải' },
        ],
      },
    },
    preview: (record) => {
      if (record.preview_href) {
        return record.preview_href
      }
      if (record.entity_type === 'project_category') {
        return `/project_list/${record.entity_id}.html`
      }
      if (record.entity_type === 'project' && record.entity_slug) {
        return `/project/${record.entity_slug}`
      }
      return ''
    },
    fieldLabels: {
      caption: 'Chú Thích',
    },
    placeholders: {
      entity_id: 'Chọn bản ghi danh mục hoặc dự án từ danh sách',
      group_name: 'hero_desktop, hero_mobile, left_gallery, right_gallery',
      caption: 'Chú thích tùy chọn để dùng về sau',
    },
    helpText: {
      entity_type: 'Dùng project_category cho ảnh hero danh mục, project cho gallery dự án.',
      entity_id: 'Danh sách sẽ tự cập nhật theo Loại Entity để bạn gắn media mà không cần nhập tay id số. Hãy dùng link xem trước nội tuyến để kiểm tra đúng đích trước khi lưu.',
      group_name: 'Các tùy chọn nhóm sẽ được lọc theo Loại Entity: danh mục dự án dùng hero_desktop/hero_mobile, dự án dùng left_gallery/right_gallery.',
      sort_order: 'Kiểm soát thứ tự ảnh trong nhóm media đã chọn.',
    },
  },
  contacts: {
    label: 'admin.entities.contacts.label',
    eyebrow: 'admin.entities.contacts.eyebrow',
    description: 'admin.entities.contacts.description',
    titleField: 'name',
    table: ['id', 'name', 'contact_type', 'postal_code', 'phone', 'email', 'is_primary', 'language_id'],
    required: ['name', 'language_id', 'latitude', 'longitude'],
    fields: ['name', 'contact_type', 'address', 'postal_code', 'phone', 'email', 'map_url', 'latitude', 'longitude', 'branch_id', 'is_primary', 'language_id'],
    fieldLabels: {
      name: 'admin.entities.contacts.fields.name',
      contact_type: 'admin.entities.contacts.fields.contact_type',
      address: 'admin.entities.contacts.fields.address',
      postal_code: 'admin.entities.contacts.fields.postal_code',
      phone: 'admin.entities.contacts.fields.phone',
      email: 'admin.entities.contacts.fields.email',
      map_url: 'admin.entities.contacts.fields.map_url',
      latitude: 'admin.entities.contacts.fields.latitude',
      longitude: 'admin.entities.contacts.fields.longitude',
      branch_id: 'admin.entities.contacts.fields.branch_id',
      is_primary: 'admin.entities.contacts.fields.is_primary',
      language_id: 'admin.entities.contacts.fields.language_id',
    }
  },
  honors: {
    label: 'admin.entities.honors.label',
    eyebrow: 'admin.entities.honors.eyebrow',
    description: 'admin.entities.honors.description',
    titleField: 'title',
    table: ['id', 'title', 'award_category', 'issuer', 'sort_order', 'is_active'],
    required: ['title', 'language_id'],
    fields: ['title', 'description', 'award_year', 'award_category', 'project_id', 'image_id', 'issuer', 'language_id', 'sort_order', 'is_active'],
    preview: () => '/honors',
    statusOptions: CONTENT_STATUS_OPTIONS,
    defaultStatus: 'published',
    fieldLabels: {
      title: 'admin.entities.honors.fields.title',
      description: 'admin.entities.honors.fields.description',
      award_year: 'admin.entities.honors.fields.award_year',
      award_category: 'admin.entities.honors.fields.award_category',
      project_id: 'admin.entities.honors.fields.project_id',
      image_id: 'admin.entities.honors.fields.image_id',
      issuer: 'admin.entities.honors.fields.issuer',
      language_id: 'admin.entities.honors.fields.language_id',
      sort_order: 'admin.entities.honors.fields.sort_order',
      is_active: 'admin.entities.honors.fields.is_active',
    },
    placeholders: {
      title: 'Ví dụ: Hình ảnh nhà máy',
      description: 'Mô tả ngắn cho mục năng lực này.',
      award_year: '2024',
      award_category: 'factory_images / production_technology / output / certificate',
      issuer: 'Ví dụ: Nhà máy Bắc Kinh',
    },
    helpText: {
      award_category: 'Dùng để phân nhóm nội dung năng lực: factory_images, production_technology, output, certificate.',
      image_id: 'Ảnh thực tế của nhà máy, máy móc hoặc chứng nhận. Đây là nội dung công khai của trang Năng lực.',
      sort_order: 'Dùng 10, 20, 30... để sắp xếp thứ tự hiển thị.',
      is_active: 'Chỉ mục đang hiển thị mới xuất hiện trên trang public.',
    },
  },
  videos: {
    label: 'admin.entities.videos.label',
    eyebrow: 'admin.entities.videos.eyebrow',
    description: 'admin.entities.videos.description',
    titleField: 'title',
    table: ['id', 'title', 'product_name', 'video_url', 'status'],
    required: ['title', 'product_id', 'video_url'],
    fields: ['title', 'product_id', 'video_url', 'status'],
    statusOptions: CONTENT_STATUS_OPTIONS,
    defaultStatus: 'draft',
    preview: () => '/video',
    cloudinaryAssetFolder: 'videos',
    fieldLabels: {
      title: 'admin.entities.videos.fields.title',
      product_id: 'admin.entities.videos.fields.product_id',
      product_name: 'admin.entities.videos.fields.product_name',
      video_url: 'admin.entities.videos.fields.video_url',
      status: 'admin.entities.videos.fields.status',
    },
    placeholders: {
      title: 'Vi du: Video demo san pham',
      product_id: 'Tim kiem hoac chon san pham',
      video_url: 'https://cdn.example.com/showcase/video.mp4 hoac URL YouTube/Vimeo',
    },
    helpText: {
      product_id: 'Moi video phai thuoc mot san pham. Ban co the go tim theo ten, SKU hoac slug.',
      video_url: 'Dung URL MP4/WebM truc tiep hoac lien ket YouTube/Vimeo/share hop le. Frontend se mo bang player cao cap.',
      status: 'Chi video co trang thai xuat ban moi hien thi tren trang public.',
    },
    relationEntities: {
      product_id: 'products',
    },
    featuredTableFields: ['product_name', 'video_url', 'status'],
  },
  media_assets: {
    label: 'admin.entities.media_assets.label',
    eyebrow: 'admin.entities.media_assets.eyebrow',
    description: 'admin.entities.media_assets.description',
    titleField: 'title',
    table: ['id', 'title', 'file_name', 'asset_type', 'mime_type', 'status'],
    required: ['uuid', 'url', 'asset_type'],
    fields: ['uuid', 'file_name', 'url', 'storage_path', 'asset_type', 'mime_type', 'width', 'height', 'size', 'alt_text', 'title', 'status'],
    fieldLabels: {
      title: 'admin.entities.media_assets.fields.title',
      file_name: 'admin.entities.media_assets.fields.file_name',
      asset_type: 'admin.entities.media_assets.fields.asset_type',
      mime_type: 'admin.entities.media_assets.fields.mime_type',
      status: 'admin.entities.media_assets.fields.status',
      size: 'admin.entities.media_assets.fields.size',
      width: 'admin.entities.media_assets.fields.width',
      height: 'admin.entities.media_assets.fields.height',
    },
    statusOptions: CATEGORY_STATUS_OPTIONS,
    defaultStatus: 'active',
    allowCreate: false,
    standaloneUpload: true,
  },
  site_settings: {
    label: 'admin.entities.site_settings.label',
    eyebrow: 'admin.entities.site_settings.eyebrow',
    description: 'admin.entities.site_settings.description',
    titleField: 'config_key',
    table: ['id', 'config_key', 'group_name', 'language_id'],
    required: ['config_key'],
    fields: ['config_key', 'config_value', 'language_id', 'group_name', 'description'],
    fieldLabels: {
      config_key: 'admin.entities.site_settings.fields.config_key',
      config_value: 'admin.entities.site_settings.fields.config_value',
      language_id: 'admin.entities.site_settings.fields.language_id',
      group_name: 'admin.entities.site_settings.fields.group_name',
      description: 'admin.entities.site_settings.fields.description',
    },
  },
  inquiry_submissions: {
    label: 'admin.entities.inquiry_submissions.label',
    editLabel: 'admin.entities.inquiry_submissions.edit_label',
    editorPresentation: 'modal',
    eyebrow: 'admin.entities.inquiry_submissions.eyebrow',
    description: 'admin.entities.inquiry_submissions.description',
    titleField: 'full_name',
    table: ['id', 'full_name', 'email', 'phone', 'subject', 'message', 'admin_response', 'status', 'created_at'],
    required: ['full_name', 'email', 'message'],
    fields: ['full_name', 'email', 'phone', 'company', 'subject', 'message', 'status', 'admin_response'],
    statusOptions: [
      { value: 'new', label: 'admin.entities.inquiry_submissions.status_options.new' },
      { value: 'in_progress', label: 'admin.entities.inquiry_submissions.status_options.in_progress' },
      { value: 'replied', label: 'admin.entities.inquiry_submissions.status_options.replied' },
      { value: 'resolved', label: 'admin.entities.inquiry_submissions.status_options.resolved' },
      { value: 'spam', label: 'admin.entities.inquiry_submissions.status_options.spam' },
    ],
    defaultStatus: 'new',
    previewCard: (record) => ({
      badge: 'Phản hồi',
      title: record.admin_response ? 'Đã trả lời' : 'Chưa trả lời',
      summary: record.admin_response 
        ? `Nội dung: ${record.admin_response}`
        : 'Yêu cầu này chưa có nội dung phản hồi nội bộ.',
      status: record.admin_response ? 'resolved' : 'warning',
    }),
    fieldLabels: {
      full_name: 'admin.entities.inquiry_submissions.fields.full_name',
      email: 'admin.entities.inquiry_submissions.fields.email',
      phone: 'admin.entities.inquiry_submissions.fields.phone',
      company: 'admin.entities.inquiry_submissions.fields.company',
      subject: 'admin.entities.inquiry_submissions.fields.subject',
      message: 'admin.entities.inquiry_submissions.fields.message',
      status: 'admin.entities.inquiry_submissions.fields.status',
      created_at: 'admin.entities.inquiry_submissions.fields.created_at',
      admin_response: 'admin.entities.inquiry_submissions.fields.admin_response',
    },
    placeholders: {
      admin_response: 'Ghi chú nội dung bạn đã trả lời khách hàng hoặc kết quả xử lý...',
    },
    helpText: {
      admin_response: 'Thông tin này hiện chỉ hiển thị trong quản trị để bạn theo dõi lịch sử xử lý yêu cầu.',
    },
  },
  news_posts: {
    label: 'admin.entities.news_posts.label',
    eyebrow: 'admin.entities.news_posts.eyebrow',
    description: 'admin.entities.news_posts.description',
    titleField: 'title',
    table: ['id', 'title', 'slug', 'status', 'is_featured', 'published_at', 'created_at'],
    required: ['title', 'slug'],
    fields: [
      'title', 'title_en', 'title_zh',
      'slug',
      'summary', 'summary_en', 'summary_zh',
      'content', 'content_en', 'content_zh',
      'content_json',
      'thumbnail_url', 'image_id', 'author',
      'status', 'is_featured', 'published_at',
      'meta_title', 'meta_title_en', 'meta_title_zh',
      'meta_description', 'meta_description_en', 'meta_description_zh',
      'sort_order',
    ],
    statusOptions: CONTENT_STATUS_OPTIONS,
    defaultStatus: 'draft',
    fieldLabels: {
      title: 'admin.entities.news_posts.fields.title',
      slug: 'admin.entities.news_posts.fields.slug',
      summary: 'admin.entities.news_posts.fields.summary',
      content: 'admin.entities.news_posts.fields.content',
      content_json: 'admin.entities.news_posts.fields.content_json',
      thumbnail_url: 'admin.entities.news_posts.fields.thumbnail_url',
      image_id: 'admin.entities.news_posts.fields.image_id',
      author: 'admin.entities.news_posts.fields.author',
      status: 'admin.entities.news_posts.fields.status',
      is_featured: 'admin.entities.news_posts.fields.is_featured',
      published_at: 'admin.entities.news_posts.fields.published_at',
      meta_title: 'admin.entities.news_posts.fields.meta_title',
      meta_description: 'admin.entities.news_posts.fields.meta_description',
      sort_order: 'admin.entities.news_posts.fields.sort_order',
    },
    placeholders: {
      title: 'Nhập tiêu đề bài viết...',
      title_en: 'English article title...',
      title_zh: '中文文章标题...',
      slug: 'tu-dong-tao-tu-tieu-de',
      summary: 'Mô tả ngắn cho bài viết...',
      summary_en: 'Short English summary...',
      summary_zh: '中文摘要...',
    },
  },
  product_categories: {
    label: 'admin.entities.product_categories.label',
    eyebrow: 'admin.entities.product_categories.eyebrow',
    description: 'admin.entities.product_categories.description',
    titleField: 'name',
    editorPresentation: 'modal',
    table: ['id', 'name', 'parent_name', 'slug', 'sort_order', 'is_active'],
    required: ['name', 'slug'],
    fields: ['name', 'name_en', 'name_zh', 'slug', 'parent_id', 'description', 'description_en', 'description_zh', 'image_url', 'sort_order', 'is_active'],
    relationEntities: {
      parent_id: 'product_categories',
    },
    fieldLabels: {
      name: 'admin.entities.product_categories.fields.name',
      slug: 'admin.entities.product_categories.fields.slug',
      parent_id: 'admin.entities.product_categories.fields.parent_id',
      parent_name: 'admin.entities.product_categories.fields.parent_name',
      description: 'admin.entities.product_categories.fields.description',
      image_url: 'admin.entities.product_categories.fields.image_url',
      sort_order: 'admin.entities.product_categories.fields.sort_order',
      is_active: 'admin.entities.product_categories.fields.is_active',
    },
    placeholders: {
      name: 'Ví dụ: Sàn Gỗ',
      name_en: 'Example: Wooden Flooring',
      name_zh: '例如：木地板',
      slug: 'san-go',
      parent_id: 'Để trống nếu là danh mục gốc',
      description: 'Mô tả ngắn về danh mục sản phẩm.',
      image_url: 'https://cdn.example.com/category-thumbnail.jpg',
    },
    helpText: {
      slug: 'Dùng cho URL và lọc sản phẩm. Viết thường, không dấu, dùng dấu gạch ngang.',
      parent_id: 'Chọn danh mục cha để tạo danh mục con. Để trống nếu là danh mục cấp 1.',
      sort_order: 'Dùng 10, 20, 30... để dễ sắp xếp lại sau này.',
    },
    preview: (record) => `/products?category=${record.slug}`,
  },
  products: {
    label: 'admin.entities.products.label',
    eyebrow: 'admin.entities.products.eyebrow',
    description: 'admin.entities.products.description',
    titleField: 'name',
    editorPresentation: 'modal',
    table: ['id', 'image_url', 'name', 'sku', 'original_price', 'sale_price', 'stock_quantity', 'category_id', 'sort_order', 'is_active'],
    required: ['name', 'slug'],
    fields: [
      'name', 'name_en', 'name_zh',
      'slug', 'sku', 'category_id',
      'image_url',
      'gallery_urls',
      'original_price', 'sale_price', 'stock_quantity',
      'short_desc', 'short_desc_en', 'short_desc_zh',
      'full_desc', 'full_desc_en', 'full_desc_zh',
      'size', 'size_en', 'size_zh',
      'material', 'material_en', 'material_zh',
      'color', 'color_en', 'color_zh',
      'use_case', 'use_case_en', 'use_case_zh',
      'video_url', 'catalog_pdf_url',
      'sort_order', 'is_active',
    ],
    cloudinaryAssetFolder: 'products',
    mediaUploadTargetField: 'image_url',
    mediaUploadAccept: 'image/*,video/*,application/pdf',
    fieldLabels: {
      name: 'admin.entities.products.fields.name',
      slug: 'admin.entities.products.fields.slug',
      sku: 'admin.entities.products.fields.sku',
      category_id: 'admin.entities.products.fields.category_id',
      image_url: 'admin.entities.products.fields.image_url',
      gallery_urls: 'admin.entities.products.fields.gallery_urls',
      original_price: 'admin.entities.products.fields.original_price',
      sale_price: 'admin.entities.products.fields.sale_price',
      stock_quantity: 'admin.entities.products.fields.stock_quantity',
      short_desc: 'admin.entities.products.fields.short_desc',
      full_desc: 'admin.entities.products.fields.full_desc',
      size: 'admin.entities.products.fields.size',
      material: 'admin.entities.products.fields.material',
      color: 'admin.entities.products.fields.color',
      use_case: 'admin.entities.products.fields.use_case',
      video_url: 'admin.entities.products.fields.video_url',
      catalog_pdf_url: 'admin.entities.products.fields.catalog_pdf_url',
      sort_order: 'admin.entities.products.fields.sort_order',
      is_active: 'admin.entities.products.fields.is_active',
    },
    placeholders: {
      name: 'Ví dụ: Sàn Gỗ Sồi Tự Nhiên',
      slug: 'san-go-soi-tu-nhien',
      sku: 'FLR-OAK-001',
      image_url: 'Dán link ảnh gốc sản phẩm hoặc upload phía trên.',
      gallery_urls: 'Mỗi dòng là một ảnh liên quan. Upload vào mục này sẽ tự nối thêm URL mới.',
      original_price: 'Ví dụ: 1250000',
      sale_price: 'Ví dụ: 990000',
      stock_quantity: 'Ví dụ: 120',
      short_desc: 'Mô tả ngắn hiển thị trên thẻ sản phẩm.',
      full_desc: 'Mô tả đầy đủ hiển thị trên trang chi tiết sản phẩm.',
      size: 'Ví dụ: 1220 × 150 × 15 mm',
      material: 'Ví dụ: Gỗ Sồi Trắng (Oak)',
      color: 'Ví dụ: Nâu vàng tự nhiên',
      use_case: 'Ví dụ: Phòng ngủ, phòng khách, văn phòng',
      video_url: 'Dán link YouTube/Cloudinary hoặc chọn tệp tải lên.',
      catalog_pdf_url: 'Link file PDF catalog.',
    },
    helpText: {
      sku: 'Mã sản phẩm duy nhất. Ví dụ: OS.01',
      category_id: 'Chọn danh mục chứa sản phẩm này.',
      image_url: 'Đây là ảnh chính/ảnh gốc của sản phẩm, dùng làm ảnh đại diện.',
      gallery_urls: 'Danh sách ảnh liên quan. Có thể dán nhiều URL hoặc upload vào đúng mục này để tự thêm mới.',
      original_price: 'Giá niêm yết/gốc của sản phẩm. FE sẽ ưu tiên dùng trường này khi không có giá khuyến mãi.',
      sale_price: 'Giá bán thực tế khi đang khuyến mãi. Để trống hoặc 0 nếu sản phẩm không giảm giá.',
      stock_quantity: 'Số lượng còn lại trong kho. Hệ thống dùng giá trị này để hiển thị còn hàng/hết hàng và giới hạn số lượng mua.',
      video_url: 'Link YouTube embed hoặc link MP4 tải lên. Để trống nếu không có.',
      catalog_pdf_url: 'Link file PDF catalog tải lên hoặc dán URL.',
    },
    relationEntities: {
      category_id: 'product_categories',
    },
    preview: (record) => `/products/${record.slug}`,
    featuredTableFields: ['image_url', 'sale_price', 'stock_quantity', 'is_active'],
  },
  users: {
    label: 'admin.entities.users.label',
    eyebrow: 'admin.entities.users.eyebrow',
    description: 'admin.entities.users.description',
    titleField: 'email',
    editorPresentation: 'modal',
    table: ['id', 'email', 'username', 'phone', 'role', 'is_active', 'last_login_at', 'created_at'],
    required: ['email'],
    fields: ['email', 'username', 'phone', 'avatar_url', 'role', 'password', 'is_active'],
    fieldLabels: {
      email: 'admin.entities.users.fields.email',
      username: 'admin.entities.users.fields.username',
      phone: 'admin.entities.users.fields.phone',
      avatar_url: 'admin.entities.users.fields.avatar_url',
      role: 'admin.entities.users.fields.role',
      password: 'admin.entities.users.fields.password',
      is_active: 'admin.entities.users.fields.is_active',
      last_login_at: 'admin.entities.users.fields.last_login_at',
      created_at: 'admin.entities.users.fields.created_at',
    },
    placeholders: {
      email: 'admin.entities.users.placeholders.email',
      username: 'admin.entities.users.placeholders.username',
      phone: 'admin.entities.users.placeholders.phone',
      avatar_url: 'admin.entities.users.placeholders.avatar_url',
      password: 'admin.entities.users.placeholders.password',
    },
    selectOptions: {
      role: [
        { value: 'user', label: 'admin.entities.users.role_options.user' },
        { value: 'admin', label: 'admin.entities.users.role_options.admin' },
      ],
    },
    helpText: {
      avatar_url: 'admin.entities.users.help_text.avatar_url',
      role: 'admin.entities.users.help_text.role',
      password: 'admin.entities.users.help_text.password',
      is_active: 'admin.entities.users.help_text.is_active',
      username: 'admin.entities.users.help_text.username',
    },
    featuredTableFields: ['email', 'role', 'is_active'],
  },
  orders: {
    label: 'admin.entities.orders.label',
    editLabel: 'admin.entities.orders.edit_label',
    eyebrow: 'admin.entities.orders.eyebrow',
    description: 'admin.entities.orders.description',
    titleField: 'code',
    editorPresentation: 'modal',
    table: [
      'id',
      'code',
      'customer_name',
      'customer_phone',
      'payment_method',
      'status',
      'payment_status',
      'total_amount',
      'placed_at',
    ],
    required: [],
    fields: ['status', 'payment_status', 'note'],
    statusOptions: [
      { value: 'pending_confirmation', label: 'admin.entities.orders.status_options.pending_confirmation' },
      { value: 'confirmed', label: 'admin.entities.orders.status_options.confirmed' },
      { value: 'processing', label: 'admin.entities.orders.status_options.processing' },
      { value: 'shipping', label: 'admin.entities.orders.status_options.shipping' },
      { value: 'delivered', label: 'admin.entities.orders.status_options.delivered' },
      { value: 'cancelled', label: 'admin.entities.orders.status_options.cancelled' },
    ],
    selectOptions: {
      payment_status: [
        { value: 'unpaid', label: 'admin.entities.orders.payment_status_options.unpaid' },
        { value: 'paid', label: 'admin.entities.orders.payment_status_options.paid' },
        { value: 'pending', label: 'admin.entities.orders.payment_status_options.pending' },
      ],
      payment_method: [
        { value: 'cod', label: 'admin.entities.orders.payment_method_options.cod' },
        { value: 'vnpay', label: 'admin.entities.orders.payment_method_options.vnpay' },
        { value: 'bank_transfer', label: 'admin.entities.orders.payment_method_options.bank_transfer' },
      ],
    },
    fieldLabels: {
      code: 'admin.entities.orders.fields.code',
      customer_name: 'admin.entities.orders.fields.customer_name',
      customer_phone: 'admin.entities.orders.fields.customer_phone',
      customer_email: 'admin.entities.orders.fields.customer_email',
      shipping_address: 'admin.entities.orders.fields.shipping_address',
      payment_method: 'admin.entities.orders.fields.payment_method',
      payment_method_label: 'admin.entities.orders.fields.payment_method_label',
      payment_status: 'admin.entities.orders.fields.payment_status',
      payment_status_label: 'admin.entities.orders.fields.payment_status_label',
      status: 'admin.entities.orders.fields.status',
      status_label: 'admin.entities.orders.fields.status_label',
      subtotal_amount: 'admin.entities.orders.fields.subtotal_amount',
      shipping_fee: 'admin.entities.orders.fields.shipping_fee',
      discount_amount: 'admin.entities.orders.fields.discount_amount',
      total_amount: 'admin.entities.orders.fields.total_amount',
      currency: 'admin.entities.orders.fields.currency',
      item_count: 'admin.entities.orders.fields.item_count',
      placed_at: 'admin.entities.orders.fields.placed_at',
      created_at: 'admin.entities.orders.fields.created_at',
      updated_at: 'admin.entities.orders.fields.updated_at',
      note: 'admin.entities.orders.fields.note',
    },
    placeholders: {
      note: 'Ví dụ: khách yêu cầu giao giờ hành chính, xác nhận qua Zalo...',
    },
    helpText: {
      status: 'Chỉ nên chuyển tuần tự theo quy trình COD: chờ xác nhận → đã xác nhận → chuẩn bị hàng → đang giao → đã giao.',
      payment_status: 'COD thường để “Chưa thanh toán” cho đến khi đơn được giao và thu tiền thành công.',
      note: 'Ghi chú này giúp đội vận hành theo dõi các yêu cầu đặc biệt của khách hoặc diễn biến xử lý đơn.',
    },
    featuredTableFields: ['code', 'status_label', 'payment_status_label'],
    allowCreate: false,
  },
}

export const ADMIN_SECTION_GROUPS = [
  { title: 'admin.sidebar.overview', items: [{ key: 'dashboard', label: 'admin.sidebar.dashboard' }] },
  {
    title: 'admin.sidebar.system',
    items: [
      { key: 'navigation', label: 'admin.sidebar.navigation' },
      { key: 'site_settings', label: 'admin.sidebar.site_settings' },
      { key: 'banners', label: 'admin.sidebar.banners' },
      { key: 'users', label: 'admin.sidebar.accounts' },
    ],
  },
  {
    title: 'admin.sidebar.about',
    items: [{ key: 'content_block_items', label: 'admin.sidebar.about' }],
  },
  {
    title: 'admin.sidebar.honors',
    items: [
      {
        key: 'capability_settings',
        label: 'admin.sidebar.capability_settings',
      },
      {
        key: 'honor_categories',
        label: 'admin.sidebar.honor_categories',
      },
      {
        key: 'honors',
        label: 'admin.sidebar.honors',
      },
      {
        key: 'media_assets',
        label: 'admin.sidebar.media',
      },
    ],
  },
  {
    title: 'admin.sidebar.content',
    items: [
      { key: 'products', label: 'admin.sidebar.products' },
      { key: 'product_categories', label: 'admin.sidebar.categories' },
      { key: 'videos', label: 'admin.sidebar.videos' },
      { key: 'news_posts', label: 'admin.sidebar.news' },
      { key: 'projects', label: 'admin.sidebar.projects' },
      { key: 'contacts', label: 'admin.sidebar.contacts' },
      { key: 'inquiry_submissions', label: 'admin.sidebar.inquiries' },
    ],
  },
  {
    title: 'admin.sidebar.orders_customers',
    items: [
      { key: 'orders', label: 'admin.sidebar.orders' },
      { key: 'users', label: 'admin.sidebar.users' },
    ],
  },
]

function flattenSectionItems(items, collector = []) {
  for (const item of items || []) {
    collector.push(item)
    if (Array.isArray(item.children) && item.children.length) {
      flattenSectionItems(item.children, collector)
    }
  }
  return collector
}

export const ADMIN_SECTION_INDEX = Object.fromEntries(ADMIN_SECTION_GROUPS.flatMap((group) => flattenSectionItems(group.items)).map((item) => [item.key, item]))

