export const ENTITY_MANAGER_CONFIGS = {
  pages: {
    label: 'Pages',
    eyebrow: 'Page content',
    description: 'Manage page slugs, summary, body, SEO, language, and ordering.',
    titleField: 'title',
    table: ['id', 'title', 'slug', 'page_type', 'status', 'language_id', 'sort_order'],
    required: ['slug', 'language_id'],
    fields: ['slug', 'title', 'summary', 'body', 'page_type', 'language_id', 'parent_id', 'status', 'meta_title', 'meta_description', 'sort_order'],
    preview: (record) => `/${record.slug}`,
  },
  page_sections: {
    label: 'Page Sections',
    eyebrow: 'Page structure',
    description: 'Manage page sections that belong to a page and control anchors, images, and ordering.',
    titleField: 'title',
    table: ['id', 'page_id', 'title', 'anchor', 'section_type', 'sort_order'],
    required: ['page_id'],
    fields: ['page_id', 'anchor', 'title', 'content', 'image_id', 'section_type', 'sort_order'],
  },
  content_blocks: {
    label: 'Content Blocks',
    eyebrow: 'Reusable blocks',
    description: 'Manage reusable content blocks attached to a page, project, or branch.',
    titleField: 'title',
    table: ['id', 'entity_type', 'entity_id', 'block_key', 'block_type', 'sort_order'],
    required: ['entity_type', 'entity_id', 'block_key', 'block_type'],
    fields: ['entity_type', 'entity_id', 'language_id', 'block_key', 'title', 'subtitle', 'content', 'block_type', 'sort_order'],
  },
  content_block_items: {
    label: 'Content Block Items',
    eyebrow: 'Block children',
    description: 'Manage the child records rendered inside a content block.',
    titleField: 'title',
    table: ['id', 'block_id', 'title', 'item_key', 'sort_order'],
    required: ['block_id'],
    fields: ['block_id', 'item_key', 'title', 'subtitle', 'content', 'link', 'image_id', 'metadata_json', 'sort_order'],
  },
  banners: {
    label: 'Banners',
    eyebrow: 'Hero and section banners',
    description: 'Manage banners, CTA buttons, type, language, and display order.',
    titleField: 'title',
    table: ['id', 'title', 'banner_type', 'language_id', 'sort_order', 'is_active'],
    required: ['language_id'],
    fields: ['title', 'subtitle', 'body', 'image_id', 'link', 'button_text', 'banner_type', 'language_id', 'sort_order', 'is_active'],
  },
  post_categories: {
    label: 'Post Categories',
    eyebrow: 'News taxonomy',
    description: 'Manage categories used by posts and news pages.',
    titleField: 'name',
    table: ['id', 'name', 'slug', 'status', 'sort_order'],
    required: ['name', 'slug'],
    fields: ['name', 'slug', 'description', 'parent_id', 'sort_order', 'status'],
  },
  posts: {
    label: 'Posts',
    eyebrow: 'News content',
    description: 'Manage post content, category, slug, publish date, SEO, and main image.',
    titleField: 'title',
    table: ['id', 'title', 'slug', 'category_id', 'status', 'published_at'],
    required: ['title', 'slug', 'language_id'],
    fields: ['title', 'slug', 'category_id', 'summary', 'body', 'published_at', 'author', 'image_id', 'language_id', 'status', 'meta_title', 'meta_description'],
    preview: (record) => `/news/${record.slug}`,
  },
  project_categories: {
    label: 'Project Categories',
    eyebrow: 'Project taxonomy',
    description: 'Manage categories used by project listing and detail pages.',
    titleField: 'name',
    table: ['id', 'name', 'slug', 'status', 'sort_order'],
    required: ['name', 'slug'],
    fields: ['name', 'slug', 'description', 'parent_id', 'sort_order', 'status'],
  },
  projects: {
    label: 'Projects',
    eyebrow: 'Project content',
    description: 'Manage project detail content, location, year, images, and SEO.',
    titleField: 'title',
    table: ['id', 'title', 'slug', 'category_id', 'project_year', 'status'],
    required: ['title', 'slug', 'language_id'],
    fields: ['title', 'slug', 'category_id', 'summary', 'body', 'location', 'project_year', 'image_id', 'hero_image_id', 'language_id', 'status', 'meta_title', 'meta_description'],
    preview: (record) => `/project/${record.slug}`,
  },
  branches: {
    label: 'Branches',
    eyebrow: 'Subsidiaries and branches',
    description: 'Manage subsidiary pages, branch details, contact info, and media.',
    titleField: 'name',
    table: ['id', 'name', 'slug', 'branch_type', 'language_id', 'is_active'],
    required: ['name', 'slug', 'language_id'],
    fields: ['name', 'slug', 'branch_type', 'address', 'city', 'region', 'phone', 'email', 'map_url', 'parent_id', 'is_active', 'language_id', 'summary', 'body', 'image_id', 'hero_image_id', 'meta_title', 'meta_description'],
    preview: (record) => `/subsidiary_Detail/${record.slug}.html`,
  },
  contacts: {
    label: 'Contacts',
    eyebrow: 'Contact information',
    description: 'Manage contact points, map links, phone numbers, email, and branch assignments.',
    titleField: 'name',
    table: ['id', 'name', 'contact_type', 'phone', 'email', 'is_primary', 'language_id'],
    required: ['name', 'language_id'],
    fields: ['name', 'contact_type', 'address', 'phone', 'email', 'map_url', 'latitude', 'longitude', 'branch_id', 'is_primary', 'language_id'],
  },
  honors: {
    label: 'Honors',
    eyebrow: 'Awards and certifications',
    description: 'Manage honors, award year, issuer, linked project, and image.',
    titleField: 'title',
    table: ['id', 'title', 'award_year', 'award_category', 'issuer', 'sort_order'],
    required: ['title', 'language_id'],
    fields: ['title', 'description', 'award_year', 'award_category', 'project_id', 'image_id', 'issuer', 'language_id', 'sort_order'],
    preview: () => '/honors',
  },
  videos: {
    label: 'Videos',
    eyebrow: 'Video gallery',
    description: 'Manage video title, description, source URL, thumbnail, and publish status.',
    titleField: 'title',
    table: ['id', 'title', 'video_url', 'language_id', 'sort_order', 'status'],
    required: ['title', 'video_url', 'language_id'],
    fields: ['title', 'description', 'video_url', 'thumbnail_id', 'language_id', 'sort_order', 'status'],
    preview: () => '/video',
  },
  media_assets: {
    label: 'Media Library',
    eyebrow: 'Uploaded assets',
    description: 'Upload, review, and update images, video files, or PDF assets used across the site.',
    titleField: 'title',
    table: ['id', 'title', 'file_name', 'asset_type', 'mime_type', 'status'],
    required: ['uuid', 'url', 'asset_type'],
    fields: ['uuid', 'file_name', 'url', 'storage_path', 'asset_type', 'mime_type', 'width', 'height', 'size', 'alt_text', 'title', 'status'],
    allowCreate: false,
    standaloneUpload: true,
  },
  site_settings: {
    label: 'Site Settings',
    eyebrow: 'Global configuration',
    description: 'Manage footer texts, contact settings, site title, and legal links.',
    titleField: 'config_key',
    table: ['id', 'config_key', 'group_name', 'language_id'],
    required: ['config_key'],
    fields: ['config_key', 'config_value', 'language_id', 'group_name', 'description'],
  },
  inquiry_submissions: {
    label: 'Inquiries',
    eyebrow: 'Contact submissions',
    description: 'Review incoming inquiry submissions and update their processing status.',
    titleField: 'subject',
    table: ['id', 'full_name', 'email', 'subject', 'status', 'created_at'],
    required: ['full_name', 'email', 'message'],
    fields: ['full_name', 'email', 'phone', 'company', 'subject', 'message', 'source_page', 'status'],
  },
}

export const ADMIN_SECTION_GROUPS = [
  { title: 'Overview', items: [{ key: 'dashboard', label: 'Dashboard' }] },
  { title: 'Navigation', items: [{ key: 'navigation', label: 'Menu Navigation' }] },
  {
    title: 'Content',
    items: [
      { key: 'posts', label: 'News Posts' },
      { key: 'videos', label: 'Videos' },
      { key: 'honors', label: 'Honors' },
      { key: 'media_assets', label: 'Media Library' },
    ],
  },
]

export const ADMIN_SECTION_INDEX = Object.fromEntries(
  ADMIN_SECTION_GROUPS.flatMap((group) => group.items).map((item) => [item.key, item])
)

